package com.twoeightnine.root.xvii.utils

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.drawable.BitmapDrawable
import android.os.Build
import android.os.Build.VERSION
import android.support.v4.util.LruCache
import android.text.SpannableStringBuilder
import android.text.style.ImageSpan
import android.view.accessibility.AccessibilityManager
import com.twoeightnine.root.xvii.R
import com.twoeightnine.root.xvii.managers.Lg
import com.twoeightnine.root.xvii.views.emoji.Emoji

object EmojiHelper {

    val emojis = mutableListOf<Emoji>()
    private val beginnings = mutableSetOf<Char>()
    private val cache: LruCache<String, Bitmap> = LruCache(10)
    private val isRiva = Build.MODEL.endsWith("S500C")

    private var size: Int = 36
    private var blind: Boolean? = null

    fun hasEmojis(text: String): Boolean {
        for (chr in text) {
            if (chr in beginnings) {
                return true
            }
        }
        return false
    }

    fun getEmojisCount(text: String): Int {
        var count = 0
        for (chr in text) {
            if (chr in beginnings) {
                count++
            }
        }
        return count
    }

    fun getEmojied(context: Context, text: String,
                   builder: SpannableStringBuilder = SpannableStringBuilder(text),
                   makeSafe: Boolean = true): SpannableStringBuilder {
        size = context.resources.getDimensionPixelSize(R.dimen.emoji_size)
        var text = text
        var makeSafe = makeSafe
        try {
            if (blind == null) {
                blind = initBlind(context)
            }
            if (isRiva && VERSION.SDK_INT == 22) {
                makeSafe = false
            }
            if (!blind!! && VERSION.SDK_INT > 15) {
                makeSafe = false
            }
            for ((key, res) in emojis) {
                var index = 0
                while (true) {
                    index = text.indexOf(key, index)
                    if (index == -1) {
                        break
                    }
                    val replace = key
                    if (makeSafe) {
                        builder.replace(index, index + key.length, replace, 0, if (blind!!) replace.length else key.length)
                        if (blind!!) {
                            text = builder.toString()
                        }
                    }
                    var bmp: Bitmap? = cache.get(res)
                    if (bmp == null) {
                        val inputStream = context.assets.open("emoji/$res")
                        bmp = BitmapFactory.decodeStream(inputStream)
                        inputStream.close()
                        cache.put(res, bmp)
                    }
                    val dr = BitmapDrawable(context.resources, bmp)
                    dr.setBounds(0, 0, size, size)
                    val span = ImageSpan(dr)
                    val replaceLength = if (makeSafe && blind!!) replace.length else key.length
                    builder.setSpan(span, index, index + replaceLength, 33)
                    index += replaceLength
                }
            }
        } catch (ex: Throwable) {
            ex.printStackTrace()
            Lg.i("error in emoji: $ex")
        }
        return builder
    }

    private fun initBlind(context: Context) = (context.getSystemService(Context.ACCESSIBILITY_SERVICE) as AccessibilityManager).isEnabled

    val facesRange = IntRange(0, 108)

    val animalsRange = IntRange(109, 202)

    val foodRange = IntRange(203, 283)

    val natureRange = IntRange(284, 346)

    val peopleRange = IntRange(347, 411)

    val symbolsRange = IntRange(412, 434)

    val otherRange = IntRange(435, 1080)

   init {
       //faces
       emojis.add(Emoji("\ud83d\ude00", "grinning-face_1f600.png"))
       emojis.add(Emoji("\ud83d\ude01", "grinning-face-with-smiling-eyes_1f601.png"))
       emojis.add(Emoji("\ud83d\ude02", "face-with-tears-of-joy_1f602.png"))
       emojis.add(Emoji("\ud83d\ude03", "smiling-face-with-open-mouth_1f603.png"))
       emojis.add(Emoji("\ud83d\ude04", "smiling-face-with-open-mouth-and-smiling-eyes_1f604.png"))
       emojis.add(Emoji("\ud83d\ude05", "smiling-face-with-open-mouth-and-cold-sweat_1f605.png"))
       emojis.add(Emoji("\ud83d\ude06", "smiling-face-with-open-mouth-and-tightly-closed-eyes_1f606.png"))
       emojis.add(Emoji("\ud83d\ude07", "smiling-face-with-halo_1f607.png"))
       emojis.add(Emoji("\ud83d\ude08", "smiling-face-with-horns_1f608.png"))
       emojis.add(Emoji("\ud83d\ude09", "winking-face_1f609.png"))
       emojis.add(Emoji("\ud83d\ude0a", "smiling-face-with-smiling-eyes_1f60a.png"))
       emojis.add(Emoji("\ud83d\ude0b", "face-savouring-delicious-food_1f60b.png"))
       emojis.add(Emoji("\ud83d\ude0c", "relieved-face_1f60c.png"))
       emojis.add(Emoji("\ud83d\ude0d", "smiling-face-with-heart-shaped-eyes_1f60d.png"))
       emojis.add(Emoji("\ud83d\ude0e", "smiling-face-with-sunglasses_1f60e.png"))
       emojis.add(Emoji("\ud83d\ude0f", "smirking-face_1f60f.png"))
       emojis.add(Emoji("\ud83d\ude10", "neutral-face_1f610.png"))
       emojis.add(Emoji("\ud83d\ude11", "expressionless-face_1f611.png"))
       emojis.add(Emoji("\ud83d\ude12", "unamused-face_1f612.png"))
       emojis.add(Emoji("\ud83d\ude13", "face-with-cold-sweat_1f613.png"))
       emojis.add(Emoji("\ud83d\ude14", "pensive-face_1f614.png"))
       emojis.add(Emoji("\ud83d\ude15", "confused-face_1f615.png"))
       emojis.add(Emoji("\ud83d\ude16", "confounded-face_1f616.png"))
       emojis.add(Emoji("\ud83d\ude17", "kissing-face_1f617.png"))
       emojis.add(Emoji("\ud83d\ude18", "face-throwing-a-kiss_1f618.png"))
       emojis.add(Emoji("\ud83d\ude19", "kissing-face-with-smiling-eyes_1f619.png"))
       emojis.add(Emoji("\ud83d\ude1a", "kissing-face-with-closed-eyes_1f61a.png"))
       emojis.add(Emoji("\ud83d\ude1b", "face-with-stuck-out-tongue_1f61b.png"))
       emojis.add(Emoji("\ud83d\ude1c", "face-with-stuck-out-tongue-and-winking-eye_1f61c.png"))
       emojis.add(Emoji("\ud83d\ude1d", "face-with-stuck-out-tongue-and-tightly-closed-eyes_1f61d.png"))
       emojis.add(Emoji("\ud83d\ude1e", "disappointed-face_1f61e.png"))
       emojis.add(Emoji("\ud83d\ude1f", "worried-face_1f61f.png"))
       emojis.add(Emoji("\ud83d\ude20", "angry-face_1f620.png"))
       emojis.add(Emoji("\ud83d\ude21", "pouting-face_1f621.png"))
       emojis.add(Emoji("\ud83d\ude22", "crying-face_1f622.png"))
       emojis.add(Emoji("\ud83d\ude23", "persevering-face_1f623.png"))
       emojis.add(Emoji("\ud83d\ude24", "face-with-look-of-triumph_1f624.png"))
       emojis.add(Emoji("\ud83d\ude25", "disappointed-but-relieved-face_1f625.png"))
       emojis.add(Emoji("\ud83d\ude26", "frowning-face-with-open-mouth_1f626.png"))
       emojis.add(Emoji("\ud83d\ude27", "anguished-face_1f627.png"))
       emojis.add(Emoji("\ud83d\ude28", "fearful-face_1f628.png"))
       emojis.add(Emoji("\ud83d\ude29", "weary-face_1f629.png"))
       emojis.add(Emoji("\ud83d\ude2a", "sleepy-face_1f62a.png"))
       emojis.add(Emoji("\ud83d\ude2b", "tired-face_1f62b.png"))
       emojis.add(Emoji("\ud83d\ude2c", "grimacing-face_1f62c.png"))
       emojis.add(Emoji("\ud83d\ude2d", "loudly-crying-face_1f62d.png"))
       emojis.add(Emoji("\ud83d\ude2e", "face-with-open-mouth_1f62e.png"))
       emojis.add(Emoji("\ud83d\ude2f", "hushed-face_1f62f.png"))
       emojis.add(Emoji("\ud83d\ude30", "face-with-open-mouth-and-cold-sweat_1f630.png"))
       emojis.add(Emoji("\ud83d\ude31", "face-screaming-in-fear_1f631.png"))
       emojis.add(Emoji("\ud83d\ude32", "astonished-face_1f632.png"))
       emojis.add(Emoji("\ud83d\ude33", "flushed-face_1f633.png"))
       emojis.add(Emoji("\ud83d\ude34", "sleeping-face_1f634.png"))
       emojis.add(Emoji("\ud83d\ude35", "dizzy-face_1f635.png"))
       emojis.add(Emoji("\ud83d\ude36", "face-without-mouth_1f636.png"))
       emojis.add(Emoji("\ud83d\ude37", "face-with-medical-mask_1f637.png"))
       emojis.add(Emoji("\ud83d\ude41", "slightly-frowning-face_1f641.png"))
       emojis.add(Emoji("\ud83d\ude42", "slightly-smiling-face_1f642.png"))
       emojis.add(Emoji("\ud83d\ude43", "upside-down-face_1f643.png"))
       emojis.add(Emoji("\ud83d\ude44", "face-with-rolling-eyes_1f644.png"))
       emojis.add(Emoji("\u2639", "white-frowning-face_2639.png"))
       emojis.add(Emoji("\u263a", "white-smiling-face_263a.png"))
       emojis.add(Emoji("\u261d", "white-up-pointing-index_261d.png"))
       emojis.add(Emoji("\u270a", "raised-fist_270a.png"))
       emojis.add(Emoji("\u270b", "raised-hand_270b.png"))
       emojis.add(Emoji("\u270c", "victory-hand_270c.png"))
       emojis.add(Emoji("\ud83d\udc40", "eyes_1f440.png"))
       emojis.add(Emoji("\ud83d\udc41", "eye_1f441.png"))
       emojis.add(Emoji("\ud83d\udc42", "ear_1f442.png"))
       emojis.add(Emoji("\ud83d\udc43", "nose_1f443.png"))
       emojis.add(Emoji("\ud83d\udc44", "mouth_1f444.png"))
       emojis.add(Emoji("\ud83d\udc45", "tongue_1f445.png"))
       emojis.add(Emoji("\ud83d\udc46", "white-up-pointing-backhand-index_1f446.png"))
       emojis.add(Emoji("\ud83d\udc47", "white-down-pointing-backhand-index_1f447.png"))
       emojis.add(Emoji("\ud83d\udc48", "white-left-pointing-backhand-index_1f448.png"))
       emojis.add(Emoji("\ud83d\udc49", "white-right-pointing-backhand-index_1f449.png"))
       emojis.add(Emoji("\ud83d\udc4a", "fisted-hand-sign_1f44a.png"))
       emojis.add(Emoji("\ud83d\udc4b", "waving-hand-sign_1f44b.png"))
       emojis.add(Emoji("\ud83d\udc4c", "ok-hand-sign_1f44c.png"))
       emojis.add(Emoji("\ud83d\udc4d", "thumbs-up-sign_1f44d.png"))
       emojis.add(Emoji("\ud83d\udc4e", "thumbs-down-sign_1f44e.png"))
       emojis.add(Emoji("\ud83d\udc4f", "clapping-hands-sign_1f44f.png"))
       emojis.add(Emoji("\ud83d\udc50", "open-hands-sign_1f450.png"))
       emojis.add(Emoji("\ud83d\udd90", "raised-hand-with-fingers-splayed_1f590.png"))
       emojis.add(Emoji("\ud83d\udd95", "reversed-hand-with-middle-finger-extended_1f595.png"))
       emojis.add(Emoji("\ud83d\udd96", "raised-hand-with-part-between-middle-and-ring-fingers_1f596.png"))
       emojis.add(Emoji("\ud83e\udd10", "zipper-mouth-face_1f910.png"))
       emojis.add(Emoji("\ud83e\udd11", "money-mouth-face_1f911.png"))
       emojis.add(Emoji("\ud83e\udd12", "face-with-thermometer_1f912.png"))
       emojis.add(Emoji("\ud83e\udd13", "nerd-face_1f913.png"))
       emojis.add(Emoji("\ud83e\udd14", "thinking-face_1f914.png"))
       emojis.add(Emoji("\ud83e\udd15", "face-with-head-bandage_1f915.png"))
       emojis.add(Emoji("\ud83e\udd16", "robot-face_1f916.png"))
       emojis.add(Emoji("\ud83e\udd17", "hugging-face_1f917.png"))
       emojis.add(Emoji("\ud83e\udd18", "sign-of-the-horns_1f918.png"))
       emojis.add(Emoji("\ud83e\udd19", "call-me-hand_1f919.png"))
       emojis.add(Emoji("\ud83e\udd1a", "raised-back-of-hand_1f91a.png"))
       emojis.add(Emoji("\ud83e\udd1b", "left-facing-fist_1f91b.png"))
       emojis.add(Emoji("\ud83e\udd1c", "right-facing-fist_1f91c.png"))
       emojis.add(Emoji("\ud83e\udd1d", "handshake_1f91d.png"))
       emojis.add(Emoji("\ud83e\udd1e", "hand-with-index-and-middle-fingers-crossed_1f91e.png"))
       emojis.add(Emoji("\ud83e\udd20", "face-with-cowboy-hat_1f920.png"))
       emojis.add(Emoji("\ud83e\udd21", "clown-face_1f921.png"))
       emojis.add(Emoji("\ud83e\udd22", "nauseated-face_1f922.png"))
       emojis.add(Emoji("\ud83e\udd23", "rolling-on-the-floor-laughing_1f923.png"))
       emojis.add(Emoji("\ud83e\udd24", "drooling-face_1f924.png"))
       emojis.add(Emoji("\ud83e\udd25", "lying-face_1f925.png"))
       emojis.add(Emoji("\ud83e\udd27", "sneezing-face_1f927.png"))
       emojis.add(Emoji("\u270d", "writing-hand_270d.png"))

//animals
       emojis.add(Emoji("\ud83d\udc00", "rat_1f400.png"))
       emojis.add(Emoji("\ud83d\udc01", "mouse_1f401.png"))
       emojis.add(Emoji("\ud83d\udc02", "ox_1f402.png"))
       emojis.add(Emoji("\ud83d\udc03", "water-buffalo_1f403.png"))
       emojis.add(Emoji("\ud83d\udc04", "cow_1f404.png"))
       emojis.add(Emoji("\ud83d\udc05", "tiger_1f405.png"))
       emojis.add(Emoji("\ud83d\udc06", "leopard_1f406.png"))
       emojis.add(Emoji("\ud83d\udc07", "rabbit_1f407.png"))
       emojis.add(Emoji("\ud83d\udc08", "cat_1f408.png"))
       emojis.add(Emoji("\ud83d\udc09", "dragon_1f409.png"))
       emojis.add(Emoji("\ud83d\udc0a", "crocodile_1f40a.png"))
       emojis.add(Emoji("\ud83d\udc0b", "whale_1f40b.png"))
       emojis.add(Emoji("\ud83d\udc0c", "snail_1f40c.png"))
       emojis.add(Emoji("\ud83d\udc0d", "snake_1f40d.png"))
       emojis.add(Emoji("\ud83d\udc0e", "horse_1f40e.png"))
       emojis.add(Emoji("\ud83d\udc0f", "ram_1f40f.png"))
       emojis.add(Emoji("\ud83d\udc10", "goat_1f410.png"))
       emojis.add(Emoji("\ud83d\udc11", "sheep_1f411.png"))
       emojis.add(Emoji("\ud83d\udc12", "monkey_1f412.png"))
       emojis.add(Emoji("\ud83d\udc13", "rooster_1f413.png"))
       emojis.add(Emoji("\ud83d\udc14", "chicken_1f414.png"))
       emojis.add(Emoji("\ud83d\udc15", "dog_1f415.png"))
       emojis.add(Emoji("\ud83d\udc16", "pig_1f416.png"))
       emojis.add(Emoji("\ud83d\udc17", "boar_1f417.png"))
       emojis.add(Emoji("\ud83d\udc18", "elephant_1f418.png"))
       emojis.add(Emoji("\ud83d\udc19", "octopus_1f419.png"))
       emojis.add(Emoji("\ud83d\udc1a", "spiral-shell_1f41a.png"))
       emojis.add(Emoji("\ud83d\udc1b", "bug_1f41b.png"))
       emojis.add(Emoji("\ud83d\udc1c", "ant_1f41c.png"))
       emojis.add(Emoji("\ud83d\udc1d", "honeybee_1f41d.png"))
       emojis.add(Emoji("\ud83d\udc1e", "lady-beetle_1f41e.png"))
       emojis.add(Emoji("\ud83d\udc1f", "fish_1f41f.png"))
       emojis.add(Emoji("\ud83d\udc20", "tropical-fish_1f420.png"))
       emojis.add(Emoji("\ud83d\udc21", "blowfish_1f421.png"))
       emojis.add(Emoji("\ud83d\udc22", "turtle_1f422.png"))
       emojis.add(Emoji("\ud83d\udc23", "hatching-chick_1f423.png"))
       emojis.add(Emoji("\ud83d\udc24", "baby-chick_1f424.png"))
       emojis.add(Emoji("\ud83d\udc25", "front-facing-baby-chick_1f425.png"))
       emojis.add(Emoji("\ud83d\udc26", "bird_1f426.png"))
       emojis.add(Emoji("\ud83d\udc27", "penguin_1f427.png"))
       emojis.add(Emoji("\ud83d\udc28", "koala_1f428.png"))
       emojis.add(Emoji("\ud83d\udc29", "poodle_1f429.png"))
       emojis.add(Emoji("\ud83d\udc2a", "dromedary-camel_1f42a.png"))
       emojis.add(Emoji("\ud83d\udc2b", "bactrian-camel_1f42b.png"))
       emojis.add(Emoji("\ud83d\udc2c", "dolphin_1f42c.png"))
       emojis.add(Emoji("\ud83d\udc2d", "mouse-face_1f42d.png"))
       emojis.add(Emoji("\ud83d\udc2e", "cow-face_1f42e.png"))
       emojis.add(Emoji("\ud83d\udc2f", "tiger-face_1f42f.png"))
       emojis.add(Emoji("\ud83d\udc30", "rabbit-face_1f430.png"))
       emojis.add(Emoji("\ud83d\udc31", "cat-face_1f431.png"))
       emojis.add(Emoji("\ud83d\udc32", "dragon-face_1f432.png"))
       emojis.add(Emoji("\ud83d\udc33", "spouting-whale_1f433.png"))
       emojis.add(Emoji("\ud83d\udc34", "horse-face_1f434.png"))
       emojis.add(Emoji("\ud83d\udc35", "monkey-face_1f435.png"))
       emojis.add(Emoji("\ud83d\udc36", "dog-face_1f436.png"))
       emojis.add(Emoji("\ud83d\udc37", "pig-face_1f437.png"))
       emojis.add(Emoji("\ud83d\udc38", "frog-face_1f438.png"))
       emojis.add(Emoji("\ud83d\udc39", "hamster-face_1f439.png"))
       emojis.add(Emoji("\ud83d\udc3a", "wolf-face_1f43a.png"))
       emojis.add(Emoji("\ud83d\udc3b", "bear-face_1f43b.png"))
       emojis.add(Emoji("\ud83d\udc3c", "panda-face_1f43c.png"))
       emojis.add(Emoji("\ud83d\udc3d", "pig-nose_1f43d.png"))
       emojis.add(Emoji("\ud83d\udc3e", "paw-prints_1f43e.png"))
       emojis.add(Emoji("\ud83d\udc3f", "chipmunk_1f43f.png"))
       emojis.add(Emoji("\ud83e\udd80", "crab_1f980.png"))
       emojis.add(Emoji("\ud83e\udd81", "lion-face_1f981.png"))
       emojis.add(Emoji("\ud83e\udd82", "scorpion_1f982.png"))
       emojis.add(Emoji("\ud83e\udd83", "turkey_1f983.png"))
       emojis.add(Emoji("\ud83e\udd84", "unicorn-face_1f984.png"))
       emojis.add(Emoji("\ud83e\udd85", "eagle_1f985.png"))
       emojis.add(Emoji("\ud83e\udd86", "duck_1f986.png"))
       emojis.add(Emoji("\ud83e\udd87", "bat_1f987.png"))
       emojis.add(Emoji("\ud83e\udd88", "shark_1f988.png"))
       emojis.add(Emoji("\ud83e\udd89", "owl_1f989.png"))
       emojis.add(Emoji("\ud83e\udd8a", "fox-face_1f98a.png"))
       emojis.add(Emoji("\ud83e\udd8b", "butterfly_1f98b.png"))
       emojis.add(Emoji("\ud83e\udd8c", "deer_1f98c.png"))
       emojis.add(Emoji("\ud83e\udd8d", "gorilla_1f98d.png"))
       emojis.add(Emoji("\ud83e\udd8e", "lizard_1f98e.png"))
       emojis.add(Emoji("\ud83e\udd8f", "rhinoceros_1f98f.png"))
       emojis.add(Emoji("\ud83e\udd90", "shrimp_1f990.png"))
       emojis.add(Emoji("\ud83e\udd91", "squid_1f991.png"))
       emojis.add(Emoji("\ud83d\ude38", "grinning-cat-face-with-smiling-eyes_1f638.png"))
       emojis.add(Emoji("\ud83d\ude39", "cat-face-with-tears-of-joy_1f639.png"))
       emojis.add(Emoji("\ud83d\ude3a", "smiling-cat-face-with-open-mouth_1f63a.png"))
       emojis.add(Emoji("\ud83d\ude3b", "smiling-cat-face-with-heart-shaped-eyes_1f63b.png"))
       emojis.add(Emoji("\ud83d\ude3c", "cat-face-with-wry-smile_1f63c.png"))
       emojis.add(Emoji("\ud83d\ude3d", "kissing-cat-face-with-closed-eyes_1f63d.png"))
       emojis.add(Emoji("\ud83d\ude3e", "pouting-cat-face_1f63e.png"))
       emojis.add(Emoji("\ud83d\ude3f", "crying-cat-face_1f63f.png"))
       emojis.add(Emoji("\ud83d\ude40", "weary-cat-face_1f640.png"))
       emojis.add(Emoji("\ud83d\ude48", "see-no-evil-monkey_1f648.png"))
       emojis.add(Emoji("\ud83d\ude49", "hear-no-evil-monkey_1f649.png"))
       emojis.add(Emoji("\ud83d\ude4a", "speak-no-evil-monkey_1f64a.png"))

//food

       emojis.add(Emoji("\ud83c\udf2d", "hot-dog_1f32d.png"))
       emojis.add(Emoji("\ud83c\udf2e", "taco_1f32e.png"))
       emojis.add(Emoji("\ud83c\udf2f", "burrito_1f32f.png"))
       emojis.add(Emoji("\ud83c\udf44", "mushroom_1f344.png"))
       emojis.add(Emoji("\ud83c\udf45", "tomato_1f345.png"))
       emojis.add(Emoji("\ud83c\udf46", "aubergine_1f346.png"))
       emojis.add(Emoji("\ud83c\udf47", "grapes_1f347.png"))
       emojis.add(Emoji("\ud83c\udf48", "melon_1f348.png"))
       emojis.add(Emoji("\ud83c\udf49", "watermelon_1f349.png"))
       emojis.add(Emoji("\ud83c\udf4a", "tangerine_1f34a.png"))
       emojis.add(Emoji("\ud83c\udf4b", "lemon_1f34b.png"))
       emojis.add(Emoji("\ud83c\udf4c", "banana_1f34c.png"))
       emojis.add(Emoji("\ud83c\udf4d", "pineapple_1f34d.png"))
       emojis.add(Emoji("\ud83c\udf4e", "red-apple_1f34e.png"))
       emojis.add(Emoji("\ud83c\udf4f", "green-apple_1f34f.png"))
       emojis.add(Emoji("\ud83c\udf50", "pear_1f350.png"))
       emojis.add(Emoji("\ud83c\udf51", "peach_1f351.png"))
       emojis.add(Emoji("\ud83c\udf52", "cherries_1f352.png"))
       emojis.add(Emoji("\ud83c\udf53", "strawberry_1f353.png"))
       emojis.add(Emoji("\ud83c\udf54", "hamburger_1f354.png"))
       emojis.add(Emoji("\ud83c\udf55", "slice-of-pizza_1f355.png"))
       emojis.add(Emoji("\ud83c\udf56", "meat-on-bone_1f356.png"))
       emojis.add(Emoji("\ud83c\udf57", "poultry-leg_1f357.png"))
       emojis.add(Emoji("\ud83c\udf58", "rice-cracker_1f358.png"))
       emojis.add(Emoji("\ud83c\udf59", "rice-ball_1f359.png"))
       emojis.add(Emoji("\ud83c\udf5a", "cooked-rice_1f35a.png"))
       emojis.add(Emoji("\ud83c\udf5b", "curry-and-rice_1f35b.png"))
       emojis.add(Emoji("\ud83c\udf5c", "steaming-bowl_1f35c.png"))
       emojis.add(Emoji("\ud83c\udf5d", "spaghetti_1f35d.png"))
       emojis.add(Emoji("\ud83c\udf5e", "bread_1f35e.png"))
       emojis.add(Emoji("\ud83c\udf5f", "french-fries_1f35f.png"))
       emojis.add(Emoji("\ud83c\udf60", "roasted-sweet-potato_1f360.png"))
       emojis.add(Emoji("\ud83c\udf61", "dango_1f361.png"))
       emojis.add(Emoji("\ud83c\udf62", "oden_1f362.png"))
       emojis.add(Emoji("\ud83c\udf63", "sushi_1f363.png"))
       emojis.add(Emoji("\ud83c\udf64", "fried-shrimp_1f364.png"))
       emojis.add(Emoji("\ud83c\udf65", "fish-cake-with-swirl-design_1f365.png"))
       emojis.add(Emoji("\ud83c\udf66", "soft-ice-cream_1f366.png"))
       emojis.add(Emoji("\ud83c\udf67", "shaved-ice_1f367.png"))
       emojis.add(Emoji("\ud83c\udf68", "ice-cream_1f368.png"))
       emojis.add(Emoji("\ud83c\udf69", "doughnut_1f369.png"))
       emojis.add(Emoji("\ud83c\udf6a", "cookie_1f36a.png"))
       emojis.add(Emoji("\ud83c\udf6b", "chocolate-bar_1f36b.png"))
       emojis.add(Emoji("\ud83c\udf6c", "candy_1f36c.png"))
       emojis.add(Emoji("\ud83c\udf6d", "lollipop_1f36d.png"))
       emojis.add(Emoji("\ud83c\udf6e", "custard_1f36e.png"))
       emojis.add(Emoji("\ud83c\udf6f", "honey-pot_1f36f.png"))
       emojis.add(Emoji("\ud83c\udf70", "shortcake_1f370.png"))
       emojis.add(Emoji("\ud83c\udf71", "bento-box_1f371.png"))
       emojis.add(Emoji("\ud83c\udf72", "pot-of-food_1f372.png"))
       emojis.add(Emoji("\ud83c\udf73", "cooking_1f373.png"))
       emojis.add(Emoji("\ud83c\udf74", "fork-and-knife_1f374.png"))
       emojis.add(Emoji("\ud83c\udf75", "teacup-without-handle_1f375.png"))
       emojis.add(Emoji("\ud83c\udf76", "sake-bottle-and-cup_1f376.png"))
       emojis.add(Emoji("\ud83c\udf77", "wine-glass_1f377.png"))
       emojis.add(Emoji("\ud83c\udf78", "cocktail-glass_1f378.png"))
       emojis.add(Emoji("\ud83c\udf79", "tropical-drink_1f379.png"))
       emojis.add(Emoji("\ud83c\udf7a", "beer-mug_1f37a.png"))
       emojis.add(Emoji("\ud83c\udf7b", "clinking-beer-mugs_1f37b.png"))
       emojis.add(Emoji("\ud83c\udf7c", "baby-bottle_1f37c.png"))
       emojis.add(Emoji("\ud83c\udf7d", "fork-and-knife-with-plate_1f37d.png"))
       emojis.add(Emoji("\ud83c\udf7e", "bottle-with-popping-cork_1f37e.png"))
       emojis.add(Emoji("\ud83c\udf7f", "popcorn_1f37f.png"))
       emojis.add(Emoji("\ud83e\udd42", "clinking-glasses_1f942.png"))
       emojis.add(Emoji("\ud83e\udd43", "tumbler-glass_1f943.png"))
       emojis.add(Emoji("\ud83e\udd50", "croissant_1f950.png"))
       emojis.add(Emoji("\ud83e\udd51", "avocado_1f951.png"))
       emojis.add(Emoji("\ud83e\udd52", "cucumber_1f952.png"))
       emojis.add(Emoji("\ud83e\udd53", "bacon_1f953.png"))
       emojis.add(Emoji("\ud83e\udd54", "potato_1f954.png"))
       emojis.add(Emoji("\ud83e\udd55", "carrot_1f955.png"))
       emojis.add(Emoji("\ud83e\udd56", "baguette-bread_1f956.png"))
       emojis.add(Emoji("\ud83e\udd57", "green-salad_1f957.png"))
       emojis.add(Emoji("\ud83e\udd58", "shallow-pan-of-food_1f958.png"))
       emojis.add(Emoji("\ud83e\udd59", "stuffed-flatbread_1f959.png"))
       emojis.add(Emoji("\ud83e\udd5a", "egg_1f95a.png"))
       emojis.add(Emoji("\ud83e\udd5b", "glass-of-milk_1f95b.png"))
       emojis.add(Emoji("\ud83e\udd5c", "peanuts_1f95c.png"))
       emojis.add(Emoji("\ud83e\udd5d", "kiwifruit_1f95d.png"))
       emojis.add(Emoji("\ud83e\udd5e", "pancakes_1f95e.png"))
       emojis.add(Emoji("\ud83e\uddc0", "cheese-wedge_1f9c0.png"))

//nature

       emojis.add(Emoji("\ud83c\udf30", "chestnut_1f330.png"))
       emojis.add(Emoji("\ud83c\udf31", "seedling_1f331.png"))
       emojis.add(Emoji("\ud83c\udf32", "evergreen-tree_1f332.png"))
       emojis.add(Emoji("\ud83c\udf33", "deciduous-tree_1f333.png"))
       emojis.add(Emoji("\ud83c\udf34", "palm-tree_1f334.png"))
       emojis.add(Emoji("\ud83c\udf35", "cactus_1f335.png"))
       emojis.add(Emoji("\ud83c\udf36", "hot-pepper_1f336.png"))
       emojis.add(Emoji("\ud83c\udf37", "tulip_1f337.png"))
       emojis.add(Emoji("\ud83c\udf38", "cherry-blossom_1f338.png"))
       emojis.add(Emoji("\ud83c\udf39", "rose_1f339.png"))
       emojis.add(Emoji("\ud83c\udf3a", "hibiscus_1f33a.png"))
       emojis.add(Emoji("\ud83c\udf3b", "sunflower_1f33b.png"))
       emojis.add(Emoji("\ud83c\udf3c", "blossom_1f33c.png"))
       emojis.add(Emoji("\ud83c\udf3d", "ear-of-maize_1f33d.png"))
       emojis.add(Emoji("\ud83c\udf3e", "ear-of-rice_1f33e.png"))
       emojis.add(Emoji("\ud83c\udf3f", "herb_1f33f.png"))
       emojis.add(Emoji("\ud83c\udf40", "four-leaf-clover_1f340.png"))
       emojis.add(Emoji("\ud83c\udf41", "maple-leaf_1f341.png"))
       emojis.add(Emoji("\ud83c\udf42", "fallen-leaf_1f342.png"))
       emojis.add(Emoji("\ud83c\udf43", "leaf-fluttering-in-wind_1f343.png"))
       emojis.add(Emoji("\ud83c\udf00", "cyclone_1f300.png"))
       emojis.add(Emoji("\ud83c\udf01", "foggy_1f301.png"))
       emojis.add(Emoji("\ud83c\udf02", "closed-umbrella_1f302.png"))
       emojis.add(Emoji("\ud83c\udf03", "night-with-stars_1f303.png"))
       emojis.add(Emoji("\ud83c\udf04", "sunrise-over-mountains_1f304.png"))
       emojis.add(Emoji("\ud83c\udf05", "sunrise_1f305.png"))
       emojis.add(Emoji("\ud83c\udf06", "cityscape-at-dusk_1f306.png"))
       emojis.add(Emoji("\ud83c\udf07", "sunset-over-buildings_1f307.png"))
       emojis.add(Emoji("\ud83c\udf08", "rainbow_1f308.png"))
       emojis.add(Emoji("\ud83c\udf09", "bridge-at-night_1f309.png"))
       emojis.add(Emoji("\ud83c\udf0a", "water-wave_1f30a.png"))
       emojis.add(Emoji("\ud83c\udf0b", "volcano_1f30b.png"))
       emojis.add(Emoji("\ud83c\udf0c", "milky-way_1f30c.png"))
       emojis.add(Emoji("\ud83c\udf0d", "earth-globe-europe-africa_1f30d.png"))
       emojis.add(Emoji("\ud83c\udf0e", "earth-globe-americas_1f30e.png"))
       emojis.add(Emoji("\ud83c\udf0f", "earth-globe-asia-australia_1f30f.png"))
       emojis.add(Emoji("\ud83c\udf10", "globe-with-meridians_1f310.png"))
       emojis.add(Emoji("\ud83c\udf11", "new-moon-symbol_1f311.png"))
       emojis.add(Emoji("\ud83c\udf12", "waxing-crescent-moon-symbol_1f312.png"))
       emojis.add(Emoji("\ud83c\udf13", "first-quarter-moon-symbol_1f313.png"))
       emojis.add(Emoji("\ud83c\udf14", "waxing-gibbous-moon-symbol_1f314.png"))
       emojis.add(Emoji("\ud83c\udf15", "full-moon-symbol_1f315.png"))
       emojis.add(Emoji("\ud83c\udf16", "waning-gibbous-moon-symbol_1f316.png"))
       emojis.add(Emoji("\ud83c\udf17", "last-quarter-moon-symbol_1f317.png"))
       emojis.add(Emoji("\ud83c\udf18", "waning-crescent-moon-symbol_1f318.png"))
       emojis.add(Emoji("\ud83c\udf19", "crescent-moon_1f319.png"))
       emojis.add(Emoji("\ud83c\udf1a", "new-moon-with-face_1f31a.png"))
       emojis.add(Emoji("\ud83c\udf1b", "first-quarter-moon-with-face_1f31b.png"))
       emojis.add(Emoji("\ud83c\udf1c", "last-quarter-moon-with-face_1f31c.png"))
       emojis.add(Emoji("\ud83c\udf1d", "full-moon-with-face_1f31d.png"))
       emojis.add(Emoji("\ud83c\udf1e", "sun-with-face_1f31e.png"))
       emojis.add(Emoji("\ud83c\udf1f", "glowing-star_1f31f.png"))
       emojis.add(Emoji("\ud83c\udf20", "shooting-star_1f320.png"))
       emojis.add(Emoji("\ud83c\udf21", "thermometer_1f321.png"))
       emojis.add(Emoji("\ud83c\udf24", "white-sun-with-small-cloud_1f324.png"))
       emojis.add(Emoji("\ud83c\udf25", "white-sun-behind-cloud_1f325.png"))
       emojis.add(Emoji("\ud83c\udf26", "white-sun-behind-cloud-with-rain_1f326.png"))
       emojis.add(Emoji("\ud83c\udf27", "cloud-with-rain_1f327.png"))
       emojis.add(Emoji("\ud83c\udf28", "cloud-with-snow_1f328.png"))
       emojis.add(Emoji("\ud83c\udf29", "cloud-with-lightning_1f329.png"))
       emojis.add(Emoji("\ud83c\udf2a", "cloud-with-tornado_1f32a.png"))
       emojis.add(Emoji("\ud83c\udf2b", "fog_1f32b.png"))
       emojis.add(Emoji("\ud83c\udf2c", "wind-blowing-face_1f32c.png"))

//people

       emojis.add(Emoji("\u26f9", "person-with-ball_26f9.png"))
       emojis.add(Emoji("\u26f7", "skier_26f7.png"))
       emojis.add(Emoji("\ud83c\udf85", "father-christmas_1f385.png"))
       emojis.add(Emoji("\ud83c\udfc2", "snowboarder_1f3c2.png"))
       emojis.add(Emoji("\ud83c\udfc3", "runner_1f3c3.png"))
       emojis.add(Emoji("\ud83c\udfc4", "surfer_1f3c4.png"))
       emojis.add(Emoji("\ud83c\udfc7", "horse-racing_1f3c7.png"))
       emojis.add(Emoji("\ud83c\udfca", "swimmer_1f3ca.png"))
       emojis.add(Emoji("\ud83c\udfcb", "weight-lifter_1f3cb.png"))
       emojis.add(Emoji("\ud83c\udfcc", "golfer_1f3cc.png"))
       emojis.add(Emoji("\ud83d\udc64", "bust-in-silhouette_1f464.png"))
       emojis.add(Emoji("\ud83d\udc65", "busts-in-silhouette_1f465.png"))
       emojis.add(Emoji("\ud83d\udc66", "boy_1f466.png"))
       emojis.add(Emoji("\ud83d\udc67", "girl_1f467.png"))
       emojis.add(Emoji("\ud83d\udc68", "man_1f468.png"))
       emojis.add(Emoji("\ud83d\udc69", "woman_1f469.png"))
       emojis.add(Emoji("\ud83d\udc6a", "family_1f46a.png"))
       emojis.add(Emoji("\ud83d\udc6b", "man-and-woman-holding-hands_1f46b.png"))
       emojis.add(Emoji("\ud83d\udc6c", "two-men-holding-hands_1f46c.png"))
       emojis.add(Emoji("\ud83d\udc6d", "two-women-holding-hands_1f46d.png"))
       emojis.add(Emoji("\ud83d\udc6e", "police-officer_1f46e.png"))
       emojis.add(Emoji("\ud83d\udc6f", "woman-with-bunny-ears_1f46f.png"))
       emojis.add(Emoji("\ud83d\udc70", "bride-with-veil_1f470.png"))
       emojis.add(Emoji("\ud83d\udc71", "person-with-blond-hair_1f471.png"))
       emojis.add(Emoji("\ud83d\udc72", "man-with-gua-pi-mao_1f472.png"))
       emojis.add(Emoji("\ud83d\udc73", "man-with-turban_1f473.png"))
       emojis.add(Emoji("\ud83d\udc74", "older-man_1f474.png"))
       emojis.add(Emoji("\ud83d\udc75", "older-woman_1f475.png"))
       emojis.add(Emoji("\ud83d\udc76", "baby_1f476.png"))
       emojis.add(Emoji("\ud83d\udc77", "construction-worker_1f477.png"))
       emojis.add(Emoji("\ud83d\udc78", "princess_1f478.png"))
       emojis.add(Emoji("\ud83d\udc7c", "baby-angel_1f47c.png"))
       emojis.add(Emoji("\ud83d\udc81", "information-desk-person_1f481.png"))
       emojis.add(Emoji("\ud83d\udc82", "guardsman_1f482.png"))
       emojis.add(Emoji("\ud83d\udc83", "dancer_1f483.png"))
       emojis.add(Emoji("\ud83d\udc84", "lipstick_1f484.png"))
       emojis.add(Emoji("\ud83d\udc85", "nail-polish_1f485.png"))
       emojis.add(Emoji("\ud83d\udc86", "face-massage_1f486.png"))
       emojis.add(Emoji("\ud83d\udc87", "haircut_1f487.png"))
       emojis.add(Emoji("\ud83d\udd74", "man-in-business-suit-levitating_1f574.png"))
       emojis.add(Emoji("\ud83d\udd75", "sleuth-or-spy_1f575.png"))
       emojis.add(Emoji("\ud83d\udd7a", "man-dancing_1f57a.png"))
       emojis.add(Emoji("\ud83d\udc8f", "kiss_1f48f.png"))
       emojis.add(Emoji("\ud83d\udc91", "couple-with-heart_1f491.png"))
       emojis.add(Emoji("\ud83d\ude45", "face-with-no-good-gesture_1f645.png"))
       emojis.add(Emoji("\ud83d\ude46", "face-with-ok-gesture_1f646.png"))
       emojis.add(Emoji("\ud83d\ude47", "person-bowing-deeply_1f647.png"))
       emojis.add(Emoji("\ud83d\ude4b", "happy-person-raising-one-hand_1f64b.png"))
       emojis.add(Emoji("\ud83d\ude4c", "person-raising-both-hands-in-celebration_1f64c.png"))
       emojis.add(Emoji("\ud83d\ude4d", "person-frowning_1f64d.png"))
       emojis.add(Emoji("\ud83d\ude4e", "person-with-pouting-face_1f64e.png"))
       emojis.add(Emoji("\ud83d\ude4f", "person-with-folded-hands_1f64f.png"))
       emojis.add(Emoji("\ud83e\udd26", "face-palm_1f926.png"))
       emojis.add(Emoji("\ud83e\udd30", "pregnant-woman_1f930.png"))
       emojis.add(Emoji("\ud83e\udd33", "selfie_1f933.png"))
       emojis.add(Emoji("\ud83e\udd34", "prince_1f934.png"))
       emojis.add(Emoji("\ud83e\udd35", "man-in-tuxedo_1f935.png"))
       emojis.add(Emoji("\ud83e\udd36", "mother-christmas_1f936.png"))
       emojis.add(Emoji("\ud83e\udd37", "shrug_1f937.png"))
       emojis.add(Emoji("\ud83e\udd38", "person-doing-cartwheel_1f938.png"))
       emojis.add(Emoji("\ud83e\udd39", "juggling_1f939.png"))
       emojis.add(Emoji("\ud83e\udd3a", "fencer_1f93a.png"))
       emojis.add(Emoji("\ud83e\udd3c", "wrestlers_1f93c.png"))
       emojis.add(Emoji("\ud83e\udd3d", "water-polo_1f93d.png"))
       emojis.add(Emoji("\ud83e\udd3e", "handball_1f93e.png"))

//symbols

       emojis.add(Emoji("\ud83d\udc93", "beating-heart_1f493.png"))
       emojis.add(Emoji("\ud83d\udc94", "broken-heart_1f494.png"))
       emojis.add(Emoji("\ud83d\udc95", "two-hearts_1f495.png"))
       emojis.add(Emoji("\ud83d\udc96", "sparkling-heart_1f496.png"))
       emojis.add(Emoji("\ud83d\udc97", "growing-heart_1f497.png"))
       emojis.add(Emoji("\ud83d\udc98", "heart-with-arrow_1f498.png"))
       emojis.add(Emoji("\ud83d\udc99", "blue-heart_1f499.png"))
       emojis.add(Emoji("\ud83d\udc9a", "green-heart_1f49a.png"))
       emojis.add(Emoji("\ud83d\udc9b", "yellow-heart_1f49b.png"))
       emojis.add(Emoji("\ud83d\udc9c", "purple-heart_1f49c.png"))
       emojis.add(Emoji("\ud83d\udc9d", "heart-with-ribbon_1f49d.png"))
       emojis.add(Emoji("\ud83d\udc9e", "revolving-hearts_1f49e.png"))
       emojis.add(Emoji("\ud83d\udc9f", "heart-decoration_1f49f.png"))
       emojis.add(Emoji("\ud83d\udca0", "diamond-shape-with-a-dot-inside_1f4a0.png"))
       emojis.add(Emoji("\ud83d\udca1", "electric-light-bulb_1f4a1.png"))
       emojis.add(Emoji("\ud83d\udca2", "anger-symbol_1f4a2.png"))
       emojis.add(Emoji("\ud83d\udca3", "bomb_1f4a3.png"))
       emojis.add(Emoji("\ud83d\udca4", "sleeping-symbol_1f4a4.png"))
       emojis.add(Emoji("\ud83d\udca5", "collision-symbol_1f4a5.png"))
       emojis.add(Emoji("\ud83d\udca6", "splashing-sweat-symbol_1f4a6.png"))
       emojis.add(Emoji("\ud83d\udca7", "droplet_1f4a7.png"))
       emojis.add(Emoji("\ud83d\udca8", "dash-symbol_1f4a8.png"))
       emojis.add(Emoji("\ud83d\udca9", "pile-of-poo_1f4a9.png"))

//other

       emojis.add(Emoji("\u203c", "double-exclamation-mark_203c.png"))
       emojis.add(Emoji("\u2049", "exclamation-question-mark_2049.png"))
       emojis.add(Emoji("\u2122", "trade-mark-sign_2122.png"))
       emojis.add(Emoji("\u2139", "information-source_2139.png"))
       emojis.add(Emoji("\u2194", "left-right-arrow_2194.png"))
       emojis.add(Emoji("\u2195", "up-down-arrow_2195.png"))
       emojis.add(Emoji("\u2196", "north-west-arrow_2196.png"))
       emojis.add(Emoji("\u2197", "north-east-arrow_2197.png"))
       emojis.add(Emoji("\u2198", "south-east-arrow_2198.png"))
       emojis.add(Emoji("\u2199", "south-west-arrow_2199.png"))
       emojis.add(Emoji("\u21a9", "leftwards-arrow-with-hook_21a9.png"))
       emojis.add(Emoji("\u21aa", "rightwards-arrow-with-hook_21aa.png"))
       emojis.add(Emoji("\u231a", "watch_231a.png"))
       emojis.add(Emoji("\u231b", "hourglass_231b.png"))
       emojis.add(Emoji("\u2328", "keyboard_2328.png"))
       emojis.add(Emoji("\u23e9", "black-right-pointing-double-triangle_23e9.png"))
       emojis.add(Emoji("\u23ea", "black-left-pointing-double-triangle_23ea.png"))
       emojis.add(Emoji("\u23eb", "black-up-pointing-double-triangle_23eb.png"))
       emojis.add(Emoji("\u23ec", "black-down-pointing-double-triangle_23ec.png"))
       emojis.add(Emoji("\u23ed", "black-right-pointing-double-triangle-with-vertical-bar_23ed.png"))
       emojis.add(Emoji("\u23ee", "black-left-pointing-double-triangle-with-vertical-bar_23ee.png"))
       emojis.add(Emoji("\u23ef", "black-right-pointing-triangle-with-double-vertical-bar_23ef.png"))
       emojis.add(Emoji("\u23f0", "alarm-clock_23f0.png"))
       emojis.add(Emoji("\u23f1", "stopwatch_23f1.png"))
       emojis.add(Emoji("\u23f2", "timer-clock_23f2.png"))
       emojis.add(Emoji("\u23f3", "hourglass-with-flowing-sand_23f3.png"))
       emojis.add(Emoji("\u23f8", "double-vertical-bar_23f8.png"))
       emojis.add(Emoji("\u23f9", "black-square-for-stop_23f9.png"))
       emojis.add(Emoji("\u23fa", "black-circle-for-record_23fa.png"))
       emojis.add(Emoji("\u24c2", "circled-latin-capital-letter-m_24c2.png"))
       emojis.add(Emoji("\u25aa", "black-small-square_25aa.png"))
       emojis.add(Emoji("\u25ab", "white-small-square_25ab.png"))
       emojis.add(Emoji("\u25b6", "black-right-pointing-triangle_25b6.png"))
       emojis.add(Emoji("\u25c0", "black-left-pointing-triangle_25c0.png"))
       emojis.add(Emoji("\u25fb", "white-medium-square_25fb.png"))
       emojis.add(Emoji("\u25fc", "black-medium-square_25fc.png"))
       emojis.add(Emoji("\u25fd", "white-medium-small-square_25fd.png"))
       emojis.add(Emoji("\u25fe", "black-medium-small-square_25fe.png"))
       emojis.add(Emoji("\u2600", "black-sun-with-rays_2600.png"))
       emojis.add(Emoji("\u2601", "cloud_2601.png"))
       emojis.add(Emoji("\u2602", "umbrella_2602.png"))
       emojis.add(Emoji("\u2603", "snowman_2603.png"))
       emojis.add(Emoji("\u2604", "comet_2604.png"))
       emojis.add(Emoji("\u260e", "black-telephone_260e.png"))
       emojis.add(Emoji("\u2611", "ballot-box-with-check_2611.png"))
       emojis.add(Emoji("\u2614", "umbrella-with-rain-drops_2614.png"))
       emojis.add(Emoji("\u2615", "hot-beverage_2615.png"))
       emojis.add(Emoji("\u2618", "shamrock_2618.png"))

       emojis.add(Emoji("\u2620", "skull-and-crossbones_2620.png"))
       emojis.add(Emoji("\u2622", "radioactive-sign_2622.png"))
       emojis.add(Emoji("\u2623", "biohazard-sign_2623.png"))
       emojis.add(Emoji("\u2626", "orthodox-cross_2626.png"))
       emojis.add(Emoji("\u262a", "star-and-crescent_262a.png"))
       emojis.add(Emoji("\u262e", "peace-symbol_262e.png"))
       emojis.add(Emoji("\u262f", "yin-yang_262f.png"))
       emojis.add(Emoji("\u2638", "wheel-of-dharma_2638.png"))

       emojis.add(Emoji("\u2648", "aries_2648.png"))
       emojis.add(Emoji("\u2649", "taurus_2649.png"))
       emojis.add(Emoji("\u264a", "gemini_264a.png"))
       emojis.add(Emoji("\u264b", "cancer_264b.png"))
       emojis.add(Emoji("\u264c", "leo_264c.png"))
       emojis.add(Emoji("\u264d", "virgo_264d.png"))
       emojis.add(Emoji("\u264e", "libra_264e.png"))
       emojis.add(Emoji("\u264f", "scorpius_264f.png"))
       emojis.add(Emoji("\u2650", "sagittarius_2650.png"))
       emojis.add(Emoji("\u2651", "capricorn_2651.png"))
       emojis.add(Emoji("\u2652", "aquarius_2652.png"))
       emojis.add(Emoji("\u2653", "pisces_2653.png"))
       emojis.add(Emoji("\u2660", "black-spade-suit_2660.png"))
       emojis.add(Emoji("\u2663", "black-club-suit_2663.png"))
       emojis.add(Emoji("\u2665", "black-heart-suit_2665.png"))
       emojis.add(Emoji("\u2666", "black-diamond-suit_2666.png"))
       emojis.add(Emoji("\u2668", "hot-springs_2668.png"))
       emojis.add(Emoji("\u267b", "black-universal-recycling-symbol_267b.png"))
       emojis.add(Emoji("\u267f", "wheelchair-symbol_267f.png"))
       emojis.add(Emoji("\u2692", "hammer-and-pick_2692.png"))
       emojis.add(Emoji("\u2693", "anchor_2693.png"))
       emojis.add(Emoji("\u2694", "crossed-swords_2694.png"))
       emojis.add(Emoji("\u2695", "staff-of-aesculapius_2695.png"))
       emojis.add(Emoji("\u2696", "scales_2696.png"))
       emojis.add(Emoji("\u2699", "gear_2699.png"))
       emojis.add(Emoji("\u269b", "atom-symbol_269b.png"))
       emojis.add(Emoji("\u269c", "fleur-de-lis_269c.png"))
       emojis.add(Emoji("\u26a0", "warning-sign_26a0.png"))
       emojis.add(Emoji("\u26a1", "high-voltage-sign_26a1.png"))
       emojis.add(Emoji("\u26aa", "medium-white-circle_26aa.png"))
       emojis.add(Emoji("\u26ab", "medium-black-circle_26ab.png"))
       emojis.add(Emoji("\u26b0", "coffin_26b0.png"))
       emojis.add(Emoji("\u26b1", "funeral-urn_26b1.png"))
       emojis.add(Emoji("\u26bd", "soccer-ball_26bd.png"))
       emojis.add(Emoji("\u26be", "baseball_26be.png"))
       emojis.add(Emoji("\u26c4", "snowman-without-snow_26c4.png"))
       emojis.add(Emoji("\u26c5", "sun-behind-cloud_26c5.png"))
       emojis.add(Emoji("\u26c8", "thunder-cloud-and-rain_26c8.png"))
       emojis.add(Emoji("\u26ce", "ophiuchus_26ce.png"))
       emojis.add(Emoji("\u26cf", "pick_26cf.png"))
       emojis.add(Emoji("\u26d1", "helmet-with-white-cross_26d1.png"))
       emojis.add(Emoji("\u26d3", "chains_26d3.png"))
       emojis.add(Emoji("\u26d4", "no-entry_26d4.png"))
       emojis.add(Emoji("\u26e9", "shinto-shrine_26e9.png"))
       emojis.add(Emoji("\u26ea", "church_26ea.png"))
       emojis.add(Emoji("\u26f0", "mountain_26f0.png"))
       emojis.add(Emoji("\u26f1", "umbrella-on-ground_26f1.png"))
       emojis.add(Emoji("\u26f2", "fountain_26f2.png"))
       emojis.add(Emoji("\u26f3", "flag-in-hole_26f3.png"))
       emojis.add(Emoji("\u26f4", "ferry_26f4.png"))
       emojis.add(Emoji("\u26f5", "sailboat_26f5.png"))

       emojis.add(Emoji("\u26f8", "ice-skate_26f8.png"))

       emojis.add(Emoji("\u26fa", "tent_26fa.png"))
       emojis.add(Emoji("\u26fd", "fuel-pump_26fd.png"))
       emojis.add(Emoji("\u2702", "black-scissors_2702.png"))
       emojis.add(Emoji("\u2705", "white-heavy-check-mark_2705.png"))
       emojis.add(Emoji("\u2708", "airplane_2708.png"))
       emojis.add(Emoji("\u2709", "envelope_2709.png"))


       emojis.add(Emoji("\u270f", "pencil_270f.png"))
       emojis.add(Emoji("\u2712", "black-nib_2712.png"))
       emojis.add(Emoji("\u2714", "heavy-check-mark_2714.png"))
       emojis.add(Emoji("\u2716", "heavy-multiplication-x_2716.png"))
       emojis.add(Emoji("\u271d", "latin-cross_271d.png"))
       emojis.add(Emoji("\u2721", "star-of-david_2721.png"))
       emojis.add(Emoji("\u2728", "sparkles_2728.png"))
       emojis.add(Emoji("\u2733", "eight-spoked-asterisk_2733.png"))
       emojis.add(Emoji("\u2734", "eight-pointed-black-star_2734.png"))
       emojis.add(Emoji("\u2744", "snowflake_2744.png"))
       emojis.add(Emoji("\u2747", "sparkle_2747.png"))
       emojis.add(Emoji("\u274c", "cross-mark_274c.png"))
       emojis.add(Emoji("\u274e", "negative-squared-cross-mark_274e.png"))
       emojis.add(Emoji("\u2753", "black-question-mark-ornament_2753.png"))
       emojis.add(Emoji("\u2754", "white-question-mark-ornament_2754.png"))
       emojis.add(Emoji("\u2755", "white-exclamation-mark-ornament_2755.png"))
       emojis.add(Emoji("\u2757", "heavy-exclamation-mark-symbol_2757.png"))
       emojis.add(Emoji("\u2763", "heavy-heart-exclamation-mark-ornament_2763.png"))
       emojis.add(Emoji("\u2764", "heavy-black-heart_2764.png"))
       emojis.add(Emoji("\u2795", "heavy-plus-sign_2795.png"))
       emojis.add(Emoji("\u2796", "heavy-minus-sign_2796.png"))
       emojis.add(Emoji("\u2797", "heavy-division-sign_2797.png"))
       emojis.add(Emoji("\u27a1", "black-rightwards-arrow_27a1.png"))
       emojis.add(Emoji("\u27b0", "curly-loop_27b0.png"))
       emojis.add(Emoji("\u27bf", "double-curly-loop_27bf.png"))
       emojis.add(Emoji("\u2934", "arrow-pointing-rightwards-then-curving-upwards_2934.png"))
       emojis.add(Emoji("\u2935", "arrow-pointing-rightwards-then-curving-downwards_2935.png"))
       emojis.add(Emoji("\u2b05", "leftwards-black-arrow_2b05.png"))
       emojis.add(Emoji("\u2b06", "upwards-black-arrow_2b06.png"))
       emojis.add(Emoji("\u2b07", "downwards-black-arrow_2b07.png"))
       emojis.add(Emoji("\u2b1b", "black-large-square_2b1b.png"))
       emojis.add(Emoji("\u2b1c", "white-large-square_2b1c.png"))
       emojis.add(Emoji("\u2b50", "white-medium-star_2b50.png"))
       emojis.add(Emoji("\u2b55", "heavy-large-circle_2b55.png"))
       emojis.add(Emoji("\u3030", "wavy-dash_3030.png"))
       emojis.add(Emoji("\u303d", "part-alternation-mark_303d.png"))
       emojis.add(Emoji("\u3297", "circled-ideograph-congratulation_3297.png"))
       emojis.add(Emoji("\u3299", "circled-ideograph-secret_3299.png"))
       emojis.add(Emoji("\ud83c\udc04", "mahjong-tile-red-dragon_1f004.png"))
       emojis.add(Emoji("\ud83c\udccf", "playing-card-black-joker_1f0cf.png"))
       emojis.add(Emoji("\ud83c\udd70", "negative-squared-latin-capital-letter-a_1f170.png"))
       emojis.add(Emoji("\ud83c\udd71", "negative-squared-latin-capital-letter-b_1f171.png"))
       emojis.add(Emoji("\ud83c\udd7e", "negative-squared-latin-capital-letter-o_1f17e.png"))
       emojis.add(Emoji("\ud83c\udd7f", "negative-squared-latin-capital-letter-p_1f17f.png"))
       emojis.add(Emoji("\ud83c\udd8e", "negative-squared-ab_1f18e.png"))
       emojis.add(Emoji("\ud83c\udd91", "squared-cl_1f191.png"))
       emojis.add(Emoji("\ud83c\udd92", "squared-cool_1f192.png"))
       emojis.add(Emoji("\ud83c\udd93", "squared-free_1f193.png"))
       emojis.add(Emoji("\ud83c\udd94", "squared-id_1f194.png"))
       emojis.add(Emoji("\ud83c\udd95", "squared-new_1f195.png"))
       emojis.add(Emoji("\ud83c\udd96", "squared-ng_1f196.png"))
       emojis.add(Emoji("\ud83c\udd97", "squared-ok_1f197.png"))
       emojis.add(Emoji("\ud83c\udd98", "squared-sos_1f198.png"))
       emojis.add(Emoji("\ud83c\udd99", "squared-up-with-exclamation-mark_1f199.png"))
       emojis.add(Emoji("\ud83c\udd9a", "squared-vs_1f19a.png"))
       emojis.add(Emoji("\ud83c\ude01", "squared-katakana-koko_1f201.png"))
       emojis.add(Emoji("\ud83c\ude02", "squared-katakana-sa_1f202.png"))
       emojis.add(Emoji("\ud83c\ude1a", "squared-cjk-unified-ideograph-7121_1f21a.png"))
       emojis.add(Emoji("\ud83c\ude2f", "squared-cjk-unified-ideograph-6307_1f22f.png"))
       emojis.add(Emoji("\ud83c\ude32", "squared-cjk-unified-ideograph-7981_1f232.png"))
       emojis.add(Emoji("\ud83c\ude33", "squared-cjk-unified-ideograph-7a7a_1f233.png"))
       emojis.add(Emoji("\ud83c\ude34", "squared-cjk-unified-ideograph-5408_1f234.png"))
       emojis.add(Emoji("\ud83c\ude35", "squared-cjk-unified-ideograph-6e80_1f235.png"))
       emojis.add(Emoji("\ud83c\ude36", "squared-cjk-unified-ideograph-6709_1f236.png"))
       emojis.add(Emoji("\ud83c\ude37", "squared-cjk-unified-ideograph-6708_1f237.png"))
       emojis.add(Emoji("\ud83c\ude38", "squared-cjk-unified-ideograph-7533_1f238.png"))
       emojis.add(Emoji("\ud83c\ude39", "squared-cjk-unified-ideograph-5272_1f239.png"))
       emojis.add(Emoji("\ud83c\ude3a", "squared-cjk-unified-ideograph-55b6_1f23a.png"))
       emojis.add(Emoji("\ud83c\ude50", "circled-ideograph-advantage_1f250.png"))
       emojis.add(Emoji("\ud83c\ude51", "circled-ideograph-accept_1f251.png"))


       emojis.add(Emoji("\ud83c\udf80", "ribbon_1f380.png"))
       emojis.add(Emoji("\ud83c\udf81", "wrapped-present_1f381.png"))
       emojis.add(Emoji("\ud83c\udf82", "birthday-cake_1f382.png"))
       emojis.add(Emoji("\ud83c\udf83", "jack-o-lantern_1f383.png"))
       emojis.add(Emoji("\ud83c\udf84", "christmas-tree_1f384.png"))

       emojis.add(Emoji("\ud83c\udf86", "fireworks_1f386.png"))
       emojis.add(Emoji("\ud83c\udf87", "firework-sparkler_1f387.png"))
       emojis.add(Emoji("\ud83c\udf88", "balloon_1f388.png"))
       emojis.add(Emoji("\ud83c\udf89", "party-popper_1f389.png"))
       emojis.add(Emoji("\ud83c\udf8a", "confetti-ball_1f38a.png"))
       emojis.add(Emoji("\ud83c\udf8b", "tanabata-tree_1f38b.png"))
       emojis.add(Emoji("\ud83c\udf8c", "crossed-flags_1f38c.png"))
       emojis.add(Emoji("\ud83c\udf8d", "pine-decoration_1f38d.png"))
       emojis.add(Emoji("\ud83c\udf8e", "japanese-dolls_1f38e.png"))
       emojis.add(Emoji("\ud83c\udf8f", "carp-streamer_1f38f.png"))
       emojis.add(Emoji("\ud83c\udf90", "wind-chime_1f390.png"))
       emojis.add(Emoji("\ud83c\udf91", "moon-viewing-ceremony_1f391.png"))
       emojis.add(Emoji("\ud83c\udf92", "school-satchel_1f392.png"))
       emojis.add(Emoji("\ud83c\udf93", "graduation-cap_1f393.png"))
       emojis.add(Emoji("\ud83c\udf96", "military-medal_1f396.png"))
       emojis.add(Emoji("\ud83c\udf97", "reminder-ribbon_1f397.png"))
       emojis.add(Emoji("\ud83c\udf99", "studio-microphone_1f399.png"))
       emojis.add(Emoji("\ud83c\udf9a", "level-slider_1f39a.png"))
       emojis.add(Emoji("\ud83c\udf9b", "control-knobs_1f39b.png"))
       emojis.add(Emoji("\ud83c\udf9e", "film-frames_1f39e.png"))
       emojis.add(Emoji("\ud83c\udf9f", "admission-tickets_1f39f.png"))
       emojis.add(Emoji("\ud83c\udfa0", "carousel-horse_1f3a0.png"))
       emojis.add(Emoji("\ud83c\udfa1", "ferris-wheel_1f3a1.png"))
       emojis.add(Emoji("\ud83c\udfa2", "roller-coaster_1f3a2.png"))
       emojis.add(Emoji("\ud83c\udfa3", "fishing-pole-and-fish_1f3a3.png"))
       emojis.add(Emoji("\ud83c\udfa4", "microphone_1f3a4.png"))
       emojis.add(Emoji("\ud83c\udfa5", "movie-camera_1f3a5.png"))
       emojis.add(Emoji("\ud83c\udfa6", "cinema_1f3a6.png"))
       emojis.add(Emoji("\ud83c\udfa7", "headphone_1f3a7.png"))
       emojis.add(Emoji("\ud83c\udfa8", "artist-palette_1f3a8.png"))
       emojis.add(Emoji("\ud83c\udfa9", "top-hat_1f3a9.png"))
       emojis.add(Emoji("\ud83c\udfaa", "circus-tent_1f3aa.png"))
       emojis.add(Emoji("\ud83c\udfab", "ticket_1f3ab.png"))
       emojis.add(Emoji("\ud83c\udfac", "clapper-board_1f3ac.png"))
       emojis.add(Emoji("\ud83c\udfad", "performing-arts_1f3ad.png"))
       emojis.add(Emoji("\ud83c\udfae", "video-game_1f3ae.png"))
       emojis.add(Emoji("\ud83c\udfaf", "direct-hit_1f3af.png"))
       emojis.add(Emoji("\ud83c\udfb0", "slot-machine_1f3b0.png"))
       emojis.add(Emoji("\ud83c\udfb1", "billiards_1f3b1.png"))
       emojis.add(Emoji("\ud83c\udfb2", "game-die_1f3b2.png"))
       emojis.add(Emoji("\ud83c\udfb3", "bowling_1f3b3.png"))
       emojis.add(Emoji("\ud83c\udfb4", "flower-playing-cards_1f3b4.png"))
       emojis.add(Emoji("\ud83c\udfb5", "musical-note_1f3b5.png"))
       emojis.add(Emoji("\ud83c\udfb6", "multiple-musical-notes_1f3b6.png"))
       emojis.add(Emoji("\ud83c\udfb7", "saxophone_1f3b7.png"))
       emojis.add(Emoji("\ud83c\udfb8", "guitar_1f3b8.png"))
       emojis.add(Emoji("\ud83c\udfb9", "musical-keyboard_1f3b9.png"))
       emojis.add(Emoji("\ud83c\udfba", "trumpet_1f3ba.png"))
       emojis.add(Emoji("\ud83c\udfbb", "violin_1f3bb.png"))
       emojis.add(Emoji("\ud83c\udfbc", "musical-score_1f3bc.png"))
       emojis.add(Emoji("\ud83c\udfbd", "running-shirt-with-sash_1f3bd.png"))
       emojis.add(Emoji("\ud83c\udfbe", "tennis-racquet-and-ball_1f3be.png"))
       emojis.add(Emoji("\ud83c\udfbf", "ski-and-ski-boot_1f3bf.png"))
       emojis.add(Emoji("\ud83c\udfc0", "basketball-and-hoop_1f3c0.png"))
       emojis.add(Emoji("\ud83c\udfc1", "chequered-flag_1f3c1.png"))

       emojis.add(Emoji("\ud83c\udfc5", "sports-medal_1f3c5.png"))
       emojis.add(Emoji("\ud83c\udfc6", "trophy_1f3c6.png"))

       emojis.add(Emoji("\ud83c\udfc8", "american-football_1f3c8.png"))
       emojis.add(Emoji("\ud83c\udfc9", "rugby-football_1f3c9.png"))

       emojis.add(Emoji("\ud83c\udfcd", "racing-motorcycle_1f3cd.png"))
       emojis.add(Emoji("\ud83c\udfce", "racing-car_1f3ce.png"))
       emojis.add(Emoji("\ud83c\udfcf", "cricket-bat-and-ball_1f3cf.png"))
       emojis.add(Emoji("\ud83c\udfd0", "volleyball_1f3d0.png"))
       emojis.add(Emoji("\ud83c\udfd1", "field-hockey-stick-and-ball_1f3d1.png"))
       emojis.add(Emoji("\ud83c\udfd2", "ice-hockey-stick-and-puck_1f3d2.png"))
       emojis.add(Emoji("\ud83c\udfd3", "table-tennis-paddle-and-ball_1f3d3.png"))
       emojis.add(Emoji("\ud83c\udfd4", "snow-capped-mountain_1f3d4.png"))
       emojis.add(Emoji("\ud83c\udfd5", "camping_1f3d5.png"))
       emojis.add(Emoji("\ud83c\udfd6", "beach-with-umbrella_1f3d6.png"))
       emojis.add(Emoji("\ud83c\udfd7", "building-construction_1f3d7.png"))
       emojis.add(Emoji("\ud83c\udfd8", "house-buildings_1f3d8.png"))
       emojis.add(Emoji("\ud83c\udfd9", "cityscape_1f3d9.png"))
       emojis.add(Emoji("\ud83c\udfda", "derelict-house-building_1f3da.png"))
       emojis.add(Emoji("\ud83c\udfdb", "classical-building_1f3db.png"))
       emojis.add(Emoji("\ud83c\udfdc", "desert_1f3dc.png"))
       emojis.add(Emoji("\ud83c\udfdd", "desert-island_1f3dd.png"))
       emojis.add(Emoji("\ud83c\udfde", "national-park_1f3de.png"))
       emojis.add(Emoji("\ud83c\udfdf", "stadium_1f3df.png"))
       emojis.add(Emoji("\ud83c\udfe0", "house-building_1f3e0.png"))
       emojis.add(Emoji("\ud83c\udfe1", "house-with-garden_1f3e1.png"))
       emojis.add(Emoji("\ud83c\udfe2", "office-building_1f3e2.png"))
       emojis.add(Emoji("\ud83c\udfe3", "japanese-post-office_1f3e3.png"))
       emojis.add(Emoji("\ud83c\udfe4", "european-post-office_1f3e4.png"))
       emojis.add(Emoji("\ud83c\udfe5", "hospital_1f3e5.png"))
       emojis.add(Emoji("\ud83c\udfe6", "bank_1f3e6.png"))
       emojis.add(Emoji("\ud83c\udfe7", "automated-teller-machine_1f3e7.png"))
       emojis.add(Emoji("\ud83c\udfe8", "hotel_1f3e8.png"))
       emojis.add(Emoji("\ud83c\udfe9", "love-hotel_1f3e9.png"))
       emojis.add(Emoji("\ud83c\udfea", "convenience-store_1f3ea.png"))
       emojis.add(Emoji("\ud83c\udfeb", "school_1f3eb.png"))
       emojis.add(Emoji("\ud83c\udfec", "department-store_1f3ec.png"))
       emojis.add(Emoji("\ud83c\udfed", "factory_1f3ed.png"))
       emojis.add(Emoji("\ud83c\udfee", "izakaya-lantern_1f3ee.png"))
       emojis.add(Emoji("\ud83c\udfef", "japanese-castle_1f3ef.png"))
       emojis.add(Emoji("\ud83c\udff0", "european-castle_1f3f0.png"))
       emojis.add(Emoji("\ud83c\udff3", "waving-white-flag_1f3f3.png"))
       emojis.add(Emoji("\ud83c\udff4", "waving-black-flag_1f3f4.png"))
       emojis.add(Emoji("\ud83c\udff5", "rosette_1f3f5.png"))
       emojis.add(Emoji("\ud83c\udff7", "label_1f3f7.png"))
       emojis.add(Emoji("\ud83c\udff8", "badminton-racquet-and-shuttlecock_1f3f8.png"))
       emojis.add(Emoji("\ud83c\udff9", "bow-and-arrow_1f3f9.png"))
       emojis.add(Emoji("\ud83c\udffa", "amphora_1f3fa.png"))
       emojis.add(Emoji("\ud83c\udffb", "emoji-modifier-fitzpatrick-type-1-2_1f3fb.png"))
       emojis.add(Emoji("\ud83c\udffc", "emoji-modifier-fitzpatrick-type-3_1f3fc.png"))
       emojis.add(Emoji("\ud83c\udffd", "emoji-modifier-fitzpatrick-type-4_1f3fd.png"))
       emojis.add(Emoji("\ud83c\udffe", "emoji-modifier-fitzpatrick-type-5_1f3fe.png"))
       emojis.add(Emoji("\ud83c\udfff", "emoji-modifier-fitzpatrick-type-6_1f3ff.png"))


       emojis.add(Emoji("\ud83d\udc51", "crown_1f451.png"))
       emojis.add(Emoji("\ud83d\udc52", "womans-hat_1f452.png"))
       emojis.add(Emoji("\ud83d\udc53", "eyeglasses_1f453.png"))
       emojis.add(Emoji("\ud83d\udc54", "necktie_1f454.png"))
       emojis.add(Emoji("\ud83d\udc55", "t-shirt_1f455.png"))
       emojis.add(Emoji("\ud83d\udc56", "jeans_1f456.png"))
       emojis.add(Emoji("\ud83d\udc57", "dress_1f457.png"))
       emojis.add(Emoji("\ud83d\udc58", "kimono_1f458.png"))
       emojis.add(Emoji("\ud83d\udc59", "bikini_1f459.png"))
       emojis.add(Emoji("\ud83d\udc5a", "womans-clothes_1f45a.png"))
       emojis.add(Emoji("\ud83d\udc5b", "purse_1f45b.png"))
       emojis.add(Emoji("\ud83d\udc5c", "handbag_1f45c.png"))
       emojis.add(Emoji("\ud83d\udc5d", "pouch_1f45d.png"))
       emojis.add(Emoji("\ud83d\udc5e", "mans-shoe_1f45e.png"))
       emojis.add(Emoji("\ud83d\udc5f", "athletic-shoe_1f45f.png"))
       emojis.add(Emoji("\ud83d\udc60", "high-heeled-shoe_1f460.png"))
       emojis.add(Emoji("\ud83d\udc61", "womans-sandal_1f461.png"))
       emojis.add(Emoji("\ud83d\udc62", "womans-boots_1f462.png"))
       emojis.add(Emoji("\ud83d\udc63", "footprints_1f463.png"))

       emojis.add(Emoji("\ud83d\udc79", "japanese-ogre_1f479.png"))
       emojis.add(Emoji("\ud83d\udc7a", "japanese-goblin_1f47a.png"))
       emojis.add(Emoji("\ud83d\udc7b", "ghost_1f47b.png"))

       emojis.add(Emoji("\ud83d\udc7d", "extraterrestrial-alien_1f47d.png"))
       emojis.add(Emoji("\ud83d\udc7e", "alien-monster_1f47e.png"))
       emojis.add(Emoji("\ud83d\udc7f", "imp_1f47f.png"))
       emojis.add(Emoji("\ud83d\udc80", "skull_1f480.png"))

       emojis.add(Emoji("\ud83d\udc88", "barber-pole_1f488.png"))
       emojis.add(Emoji("\ud83d\udc89", "syringe_1f489.png"))
       emojis.add(Emoji("\ud83d\udc8a", "pill_1f48a.png"))
       emojis.add(Emoji("\ud83d\udc8b", "kiss-mark_1f48b.png"))
       emojis.add(Emoji("\ud83d\udc8c", "love-letter_1f48c.png"))
       emojis.add(Emoji("\ud83d\udc8d", "ring_1f48d.png"))
       emojis.add(Emoji("\ud83d\udc8e", "gem-stone_1f48e.png"))

       emojis.add(Emoji("\ud83d\udc90", "bouquet_1f490.png"))

       emojis.add(Emoji("\ud83d\udc92", "wedding_1f492.png"))

       emojis.add(Emoji("\ud83d\udcaa", "flexed-biceps_1f4aa.png"))
       emojis.add(Emoji("\ud83d\udcab", "dizzy-symbol_1f4ab.png"))
       emojis.add(Emoji("\ud83d\udcac", "speech-balloon_1f4ac.png"))
       emojis.add(Emoji("\ud83d\udcad", "thought-balloon_1f4ad.png"))
       emojis.add(Emoji("\ud83d\udcae", "white-flower_1f4ae.png"))
       emojis.add(Emoji("\ud83d\udcaf", "hundred-points-symbol_1f4af.png"))
       emojis.add(Emoji("\ud83d\udcb0", "money-bag_1f4b0.png"))
       emojis.add(Emoji("\ud83d\udcb1", "currency-exchange_1f4b1.png"))
       emojis.add(Emoji("\ud83d\udcb2", "heavy-dollar-sign_1f4b2.png"))
       emojis.add(Emoji("\ud83d\udcb3", "credit-card_1f4b3.png"))
       emojis.add(Emoji("\ud83d\udcb4", "banknote-with-yen-sign_1f4b4.png"))
       emojis.add(Emoji("\ud83d\udcb5", "banknote-with-dollar-sign_1f4b5.png"))
       emojis.add(Emoji("\ud83d\udcb6", "banknote-with-euro-sign_1f4b6.png"))
       emojis.add(Emoji("\ud83d\udcb7", "banknote-with-pound-sign_1f4b7.png"))
       emojis.add(Emoji("\ud83d\udcb8", "money-with-wings_1f4b8.png"))
       emojis.add(Emoji("\ud83d\udcb9", "chart-with-upwards-trend-and-yen-sign_1f4b9.png"))
       emojis.add(Emoji("\ud83d\udcba", "seat_1f4ba.png"))
       emojis.add(Emoji("\ud83d\udcbb", "personal-computer_1f4bb.png"))
       emojis.add(Emoji("\ud83d\udcbc", "briefcase_1f4bc.png"))
       emojis.add(Emoji("\ud83d\udcbd", "minidisc_1f4bd.png"))
       emojis.add(Emoji("\ud83d\udcbe", "floppy-disk_1f4be.png"))
       emojis.add(Emoji("\ud83d\udcbf", "optical-disc_1f4bf.png"))
       emojis.add(Emoji("\ud83d\udcc0", "dvd_1f4c0.png"))
       emojis.add(Emoji("\ud83d\udcc1", "file-folder_1f4c1.png"))
       emojis.add(Emoji("\ud83d\udcc2", "open-file-folder_1f4c2.png"))
       emojis.add(Emoji("\ud83d\udcc3", "page-with-curl_1f4c3.png"))
       emojis.add(Emoji("\ud83d\udcc4", "page-facing-up_1f4c4.png"))
       emojis.add(Emoji("\ud83d\udcc5", "calendar_1f4c5.png"))
       emojis.add(Emoji("\ud83d\udcc6", "tear-off-calendar_1f4c6.png"))
       emojis.add(Emoji("\ud83d\udcc7", "card-index_1f4c7.png"))
       emojis.add(Emoji("\ud83d\udcc8", "chart-with-upwards-trend_1f4c8.png"))
       emojis.add(Emoji("\ud83d\udcc9", "chart-with-downwards-trend_1f4c9.png"))
       emojis.add(Emoji("\ud83d\udcca", "bar-chart_1f4ca.png"))
       emojis.add(Emoji("\ud83d\udccb", "clipboard_1f4cb.png"))
       emojis.add(Emoji("\ud83d\udccc", "pushpin_1f4cc.png"))
       emojis.add(Emoji("\ud83d\udccd", "round-pushpin_1f4cd.png"))
       emojis.add(Emoji("\ud83d\udcce", "paperclip_1f4ce.png"))
       emojis.add(Emoji("\ud83d\udccf", "straight-ruler_1f4cf.png"))
       emojis.add(Emoji("\ud83d\udcd0", "triangular-ruler_1f4d0.png"))
       emojis.add(Emoji("\ud83d\udcd1", "bookmark-tabs_1f4d1.png"))
       emojis.add(Emoji("\ud83d\udcd2", "ledger_1f4d2.png"))
       emojis.add(Emoji("\ud83d\udcd3", "notebook_1f4d3.png"))
       emojis.add(Emoji("\ud83d\udcd4", "notebook-with-decorative-cover_1f4d4.png"))
       emojis.add(Emoji("\ud83d\udcd5", "closed-book_1f4d5.png"))
       emojis.add(Emoji("\ud83d\udcd6", "open-book_1f4d6.png"))
       emojis.add(Emoji("\ud83d\udcd7", "green-book_1f4d7.png"))
       emojis.add(Emoji("\ud83d\udcd8", "blue-book_1f4d8.png"))
       emojis.add(Emoji("\ud83d\udcd9", "orange-book_1f4d9.png"))
       emojis.add(Emoji("\ud83d\udcda", "books_1f4da.png"))
       emojis.add(Emoji("\ud83d\udcdb", "name-badge_1f4db.png"))
       emojis.add(Emoji("\ud83d\udcdc", "scroll_1f4dc.png"))
       emojis.add(Emoji("\ud83d\udcdd", "memo_1f4dd.png"))
       emojis.add(Emoji("\ud83d\udcde", "telephone-receiver_1f4de.png"))
       emojis.add(Emoji("\ud83d\udcdf", "pager_1f4df.png"))
       emojis.add(Emoji("\ud83d\udce0", "fax-machine_1f4e0.png"))
       emojis.add(Emoji("\ud83d\udce1", "satellite-antenna_1f4e1.png"))
       emojis.add(Emoji("\ud83d\udce2", "public-address-loudspeaker_1f4e2.png"))
       emojis.add(Emoji("\ud83d\udce3", "cheering-megaphone_1f4e3.png"))
       emojis.add(Emoji("\ud83d\udce4", "outbox-tray_1f4e4.png"))
       emojis.add(Emoji("\ud83d\udce5", "inbox-tray_1f4e5.png"))
       emojis.add(Emoji("\ud83d\udce6", "package_1f4e6.png"))
       emojis.add(Emoji("\ud83d\udce7", "e-mail-symbol_1f4e7.png"))
       emojis.add(Emoji("\ud83d\udce8", "incoming-envelope_1f4e8.png"))
       emojis.add(Emoji("\ud83d\udce9", "envelope-with-downwards-arrow-above_1f4e9.png"))
       emojis.add(Emoji("\ud83d\udcea", "closed-mailbox-with-lowered-flag_1f4ea.png"))
       emojis.add(Emoji("\ud83d\udceb", "closed-mailbox-with-raised-flag_1f4eb.png"))
       emojis.add(Emoji("\ud83d\udcec", "open-mailbox-with-raised-flag_1f4ec.png"))
       emojis.add(Emoji("\ud83d\udced", "open-mailbox-with-lowered-flag_1f4ed.png"))
       emojis.add(Emoji("\ud83d\udcee", "postbox_1f4ee.png"))
       emojis.add(Emoji("\ud83d\udcef", "postal-horn_1f4ef.png"))
       emojis.add(Emoji("\ud83d\udcf0", "newspaper_1f4f0.png"))
       emojis.add(Emoji("\ud83d\udcf1", "mobile-phone_1f4f1.png"))
       emojis.add(Emoji("\ud83d\udcf2", "mobile-phone-with-rightwards-arrow-at-left_1f4f2.png"))
       emojis.add(Emoji("\ud83d\udcf3", "vibration-mode_1f4f3.png"))
       emojis.add(Emoji("\ud83d\udcf4", "mobile-phone-off_1f4f4.png"))
       emojis.add(Emoji("\ud83d\udcf5", "no-mobile-phones_1f4f5.png"))
       emojis.add(Emoji("\ud83d\udcf6", "antenna-with-bars_1f4f6.png"))
       emojis.add(Emoji("\ud83d\udcf7", "camera_1f4f7.png"))
       emojis.add(Emoji("\ud83d\udcf8", "camera-with-flash_1f4f8.png"))
       emojis.add(Emoji("\ud83d\udcf9", "video-camera_1f4f9.png"))
       emojis.add(Emoji("\ud83d\udcfa", "television_1f4fa.png"))
       emojis.add(Emoji("\ud83d\udcfb", "radio_1f4fb.png"))
       emojis.add(Emoji("\ud83d\udcfc", "videocassette_1f4fc.png"))
       emojis.add(Emoji("\ud83d\udcfd", "film-projector_1f4fd.png"))
       emojis.add(Emoji("\ud83d\udcff", "prayer-beads_1f4ff.png"))
       emojis.add(Emoji("\ud83d\udd00", "twisted-rightwards-arrows_1f500.png"))
       emojis.add(Emoji("\ud83d\udd01", "clockwise-rightwards-and-leftwards-open-circle-arrows_1f501.png"))
       emojis.add(Emoji("\ud83d\udd02", "clockwise-rightwards-and-leftwards-open-circle-arrows-with-circled-one-overlay_1f502.png"))
       emojis.add(Emoji("\ud83d\udd03", "clockwise-downwards-and-upwards-open-circle-arrows_1f503.png"))
       emojis.add(Emoji("\ud83d\udd04", "anticlockwise-downwards-and-upwards-open-circle-arrows_1f504.png"))
       emojis.add(Emoji("\ud83d\udd05", "low-brightness-symbol_1f505.png"))
       emojis.add(Emoji("\ud83d\udd06", "high-brightness-symbol_1f506.png"))
       emojis.add(Emoji("\ud83d\udd07", "speaker-with-cancellation-stroke_1f507.png"))
       emojis.add(Emoji("\ud83d\udd08", "speaker_1f508.png"))
       emojis.add(Emoji("\ud83d\udd09", "speaker-with-one-sound-wave_1f509.png"))
       emojis.add(Emoji("\ud83d\udd0a", "speaker-with-three-sound-waves_1f50a.png"))
       emojis.add(Emoji("\ud83d\udd0b", "battery_1f50b.png"))
       emojis.add(Emoji("\ud83d\udd0c", "electric-plug_1f50c.png"))
       emojis.add(Emoji("\ud83d\udd0d", "left-pointing-magnifying-glass_1f50d.png"))
       emojis.add(Emoji("\ud83d\udd0e", "right-pointing-magnifying-glass_1f50e.png"))
       emojis.add(Emoji("\ud83d\udd0f", "lock-with-ink-pen_1f50f.png"))
       emojis.add(Emoji("\ud83d\udd10", "closed-lock-with-key_1f510.png"))
       emojis.add(Emoji("\ud83d\udd11", "key_1f511.png"))
       emojis.add(Emoji("\ud83d\udd12", "lock_1f512.png"))
       emojis.add(Emoji("\ud83d\udd13", "open-lock_1f513.png"))
       emojis.add(Emoji("\ud83d\udd14", "bell_1f514.png"))
       emojis.add(Emoji("\ud83d\udd15", "bell-with-cancellation-stroke_1f515.png"))
       emojis.add(Emoji("\ud83d\udd16", "bookmark_1f516.png"))
       emojis.add(Emoji("\ud83d\udd17", "link-symbol_1f517.png"))
       emojis.add(Emoji("\ud83d\udd18", "radio-button_1f518.png"))
       emojis.add(Emoji("\ud83d\udd19", "back-with-leftwards-arrow-above_1f519.png"))
       emojis.add(Emoji("\ud83d\udd1a", "end-with-leftwards-arrow-above_1f51a.png"))
       emojis.add(Emoji("\ud83d\udd1b", "on-with-exclamation-mark-with-left-right-arrow-above_1f51b.png"))
       emojis.add(Emoji("\ud83d\udd1c", "soon-with-rightwards-arrow-above_1f51c.png"))
       emojis.add(Emoji("\ud83d\udd1d", "top-with-upwards-arrow-above_1f51d.png"))
       emojis.add(Emoji("\ud83d\udd1e", "no-one-under-eighteen-symbol_1f51e.png"))
       emojis.add(Emoji("\ud83d\udd1f", "keycap-ten_1f51f.png"))
       emojis.add(Emoji("\ud83d\udd20", "input-symbol-for-latin-capital-letters_1f520.png"))
       emojis.add(Emoji("\ud83d\udd21", "input-symbol-for-latin-small-letters_1f521.png"))
       emojis.add(Emoji("\ud83d\udd22", "input-symbol-for-numbers_1f522.png"))
       emojis.add(Emoji("\ud83d\udd23", "input-symbol-for-symbols_1f523.png"))
       emojis.add(Emoji("\ud83d\udd24", "input-symbol-for-latin-letters_1f524.png"))
       emojis.add(Emoji("\ud83d\udd25", "fire_1f525.png"))
       emojis.add(Emoji("\ud83d\udd26", "electric-torch_1f526.png"))
       emojis.add(Emoji("\ud83d\udd27", "wrench_1f527.png"))
       emojis.add(Emoji("\ud83d\udd28", "hammer_1f528.png"))
       emojis.add(Emoji("\ud83d\udd29", "nut-and-bolt_1f529.png"))
       emojis.add(Emoji("\ud83d\udd2a", "hocho_1f52a.png"))
       emojis.add(Emoji("\ud83d\udd2b", "pistol_1f52b.png"))
       emojis.add(Emoji("\ud83d\udd2c", "microscope_1f52c.png"))
       emojis.add(Emoji("\ud83d\udd2d", "telescope_1f52d.png"))
       emojis.add(Emoji("\ud83d\udd2e", "crystal-ball_1f52e.png"))
       emojis.add(Emoji("\ud83d\udd2f", "six-pointed-star-with-middle-dot_1f52f.png"))
       emojis.add(Emoji("\ud83d\udd30", "japanese-symbol-for-beginner_1f530.png"))
       emojis.add(Emoji("\ud83d\udd31", "trident-emblem_1f531.png"))
       emojis.add(Emoji("\ud83d\udd32", "black-square-button_1f532.png"))
       emojis.add(Emoji("\ud83d\udd33", "white-square-button_1f533.png"))
       emojis.add(Emoji("\ud83d\udd34", "large-red-circle_1f534.png"))
       emojis.add(Emoji("\ud83d\udd35", "large-blue-circle_1f535.png"))
       emojis.add(Emoji("\ud83d\udd36", "large-orange-diamond_1f536.png"))
       emojis.add(Emoji("\ud83d\udd37", "large-blue-diamond_1f537.png"))
       emojis.add(Emoji("\ud83d\udd38", "small-orange-diamond_1f538.png"))
       emojis.add(Emoji("\ud83d\udd39", "small-blue-diamond_1f539.png"))
       emojis.add(Emoji("\ud83d\udd3a", "up-pointing-red-triangle_1f53a.png"))
       emojis.add(Emoji("\ud83d\udd3b", "down-pointing-red-triangle_1f53b.png"))
       emojis.add(Emoji("\ud83d\udd3c", "up-pointing-small-red-triangle_1f53c.png"))
       emojis.add(Emoji("\ud83d\udd3d", "down-pointing-small-red-triangle_1f53d.png"))
       emojis.add(Emoji("\ud83d\udd49", "om-symbol_1f549.png"))
       emojis.add(Emoji("\ud83d\udd4a", "dove-of-peace_1f54a.png"))
       emojis.add(Emoji("\ud83d\udd4b", "kaaba_1f54b.png"))
       emojis.add(Emoji("\ud83d\udd4c", "mosque_1f54c.png"))
       emojis.add(Emoji("\ud83d\udd4d", "synagogue_1f54d.png"))
       emojis.add(Emoji("\ud83d\udd4e", "menorah-with-nine-branches_1f54e.png"))
       emojis.add(Emoji("\ud83d\udd50", "clock-face-one-oclock_1f550.png"))
       emojis.add(Emoji("\ud83d\udd51", "clock-face-two-oclock_1f551.png"))
       emojis.add(Emoji("\ud83d\udd52", "clock-face-three-oclock_1f552.png"))
       emojis.add(Emoji("\ud83d\udd53", "clock-face-four-oclock_1f553.png"))
       emojis.add(Emoji("\ud83d\udd54", "clock-face-five-oclock_1f554.png"))
       emojis.add(Emoji("\ud83d\udd55", "clock-face-six-oclock_1f555.png"))
       emojis.add(Emoji("\ud83d\udd56", "clock-face-seven-oclock_1f556.png"))
       emojis.add(Emoji("\ud83d\udd57", "clock-face-eight-oclock_1f557.png"))
       emojis.add(Emoji("\ud83d\udd58", "clock-face-nine-oclock_1f558.png"))
       emojis.add(Emoji("\ud83d\udd59", "clock-face-ten-oclock_1f559.png"))
       emojis.add(Emoji("\ud83d\udd5a", "clock-face-eleven-oclock_1f55a.png"))
       emojis.add(Emoji("\ud83d\udd5b", "clock-face-twelve-oclock_1f55b.png"))
       emojis.add(Emoji("\ud83d\udd5c", "clock-face-one-thirty_1f55c.png"))
       emojis.add(Emoji("\ud83d\udd5d", "clock-face-two-thirty_1f55d.png"))
       emojis.add(Emoji("\ud83d\udd5e", "clock-face-three-thirty_1f55e.png"))
       emojis.add(Emoji("\ud83d\udd5f", "clock-face-four-thirty_1f55f.png"))
       emojis.add(Emoji("\ud83d\udd60", "clock-face-five-thirty_1f560.png"))
       emojis.add(Emoji("\ud83d\udd61", "clock-face-six-thirty_1f561.png"))
       emojis.add(Emoji("\ud83d\udd62", "clock-face-seven-thirty_1f562.png"))
       emojis.add(Emoji("\ud83d\udd63", "clock-face-eight-thirty_1f563.png"))
       emojis.add(Emoji("\ud83d\udd64", "clock-face-nine-thirty_1f564.png"))
       emojis.add(Emoji("\ud83d\udd65", "clock-face-ten-thirty_1f565.png"))
       emojis.add(Emoji("\ud83d\udd66", "clock-face-eleven-thirty_1f566.png"))
       emojis.add(Emoji("\ud83d\udd67", "clock-face-twelve-thirty_1f567.png"))
       emojis.add(Emoji("\ud83d\udd6f", "candle_1f56f.png"))
       emojis.add(Emoji("\ud83d\udd70", "mantelpiece-clock_1f570.png"))
       emojis.add(Emoji("\ud83d\udd73", "hole_1f573.png"))

       emojis.add(Emoji("\ud83d\udd76", "dark-sunglasses_1f576.png"))
       emojis.add(Emoji("\ud83d\udd77", "spider_1f577.png"))
       emojis.add(Emoji("\ud83d\udd78", "spider-web_1f578.png"))
       emojis.add(Emoji("\ud83d\udd79", "joystick_1f579.png"))

       emojis.add(Emoji("\ud83d\udd87", "linked-paperclips_1f587.png"))
       emojis.add(Emoji("\ud83d\udd8a", "lower-left-ballpoint-pen_1f58a.png"))
       emojis.add(Emoji("\ud83d\udd8b", "lower-left-fountain-pen_1f58b.png"))
       emojis.add(Emoji("\ud83d\udd8c", "lower-left-paintbrush_1f58c.png"))
       emojis.add(Emoji("\ud83d\udd8d", "lower-left-crayon_1f58d.png"))

       emojis.add(Emoji("\ud83d\udda4", "black-heart_1f5a4.png"))
       emojis.add(Emoji("\ud83d\udda5", "desktop-computer_1f5a5.png"))
       emojis.add(Emoji("\ud83d\udda8", "printer_1f5a8.png"))
       emojis.add(Emoji("\ud83d\uddb1", "three-button-mouse_1f5b1.png"))
       emojis.add(Emoji("\ud83d\uddb2", "trackball_1f5b2.png"))
       emojis.add(Emoji("\ud83d\uddbc", "frame-with-picture_1f5bc.png"))
       emojis.add(Emoji("\ud83d\uddc2", "card-index-dividers_1f5c2.png"))
       emojis.add(Emoji("\ud83d\uddc3", "card-file-box_1f5c3.png"))
       emojis.add(Emoji("\ud83d\uddc4", "file-cabinet_1f5c4.png"))
       emojis.add(Emoji("\ud83d\uddd1", "wastebasket_1f5d1.png"))
       emojis.add(Emoji("\ud83d\uddd2", "spiral-note-pad_1f5d2.png"))
       emojis.add(Emoji("\ud83d\uddd3", "spiral-calendar-pad_1f5d3.png"))
       emojis.add(Emoji("\ud83d\udddc", "compression_1f5dc.png"))
       emojis.add(Emoji("\ud83d\udddd", "old-key_1f5dd.png"))
       emojis.add(Emoji("\ud83d\uddde", "rolled-up-newspaper_1f5de.png"))
       emojis.add(Emoji("\ud83d\udde1", "dagger-knife_1f5e1.png"))
       emojis.add(Emoji("\ud83d\udde3", "speaking-head-in-silhouette_1f5e3.png"))
       emojis.add(Emoji("\ud83d\udde8", "left-speech-bubble_1f5e8.png"))
       emojis.add(Emoji("\ud83d\uddef", "right-anger-bubble_1f5ef.png"))
       emojis.add(Emoji("\ud83d\uddf3", "ballot-box-with-ballot_1f5f3.png"))
       emojis.add(Emoji("\ud83d\uddfa", "world-map_1f5fa.png"))
       emojis.add(Emoji("\ud83d\uddfb", "mount-fuji_1f5fb.png"))
       emojis.add(Emoji("\ud83d\uddfc", "tokyo-tower_1f5fc.png"))
       emojis.add(Emoji("\ud83d\uddfd", "statue-of-liberty_1f5fd.png"))
       emojis.add(Emoji("\ud83d\uddfe", "silhouette-of-japan_1f5fe.png"))
       emojis.add(Emoji("\ud83d\uddff", "moyai_1f5ff.png"))




       emojis.add(Emoji("\ud83d\ude80", "rocket_1f680.png"))
       emojis.add(Emoji("\ud83d\ude81", "helicopter_1f681.png"))
       emojis.add(Emoji("\ud83d\ude82", "steam-locomotive_1f682.png"))
       emojis.add(Emoji("\ud83d\ude83", "railway-car_1f683.png"))
       emojis.add(Emoji("\ud83d\ude84", "high-speed-train_1f684.png"))
       emojis.add(Emoji("\ud83d\ude85", "high-speed-train-with-bullet-nose_1f685.png"))
       emojis.add(Emoji("\ud83d\ude86", "train_1f686.png"))
       emojis.add(Emoji("\ud83d\ude87", "metro_1f687.png"))
       emojis.add(Emoji("\ud83d\ude88", "light-rail_1f688.png"))
       emojis.add(Emoji("\ud83d\ude89", "station_1f689.png"))
       emojis.add(Emoji("\ud83d\ude8a", "tram_1f68a.png"))
       emojis.add(Emoji("\ud83d\ude8b", "tram-car_1f68b.png"))
       emojis.add(Emoji("\ud83d\ude8c", "bus_1f68c.png"))
       emojis.add(Emoji("\ud83d\ude8d", "oncoming-bus_1f68d.png"))
       emojis.add(Emoji("\ud83d\ude8e", "trolleybus_1f68e.png"))
       emojis.add(Emoji("\ud83d\ude8f", "bus-stop_1f68f.png"))
       emojis.add(Emoji("\ud83d\ude90", "minibus_1f690.png"))
       emojis.add(Emoji("\ud83d\ude91", "ambulance_1f691.png"))
       emojis.add(Emoji("\ud83d\ude92", "fire-engine_1f692.png"))
       emojis.add(Emoji("\ud83d\ude93", "police-car_1f693.png"))
       emojis.add(Emoji("\ud83d\ude94", "oncoming-police-car_1f694.png"))
       emojis.add(Emoji("\ud83d\ude95", "taxi_1f695.png"))
       emojis.add(Emoji("\ud83d\ude96", "oncoming-taxi_1f696.png"))
       emojis.add(Emoji("\ud83d\ude97", "automobile_1f697.png"))
       emojis.add(Emoji("\ud83d\ude98", "oncoming-automobile_1f698.png"))
       emojis.add(Emoji("\ud83d\ude99", "recreational-vehicle_1f699.png"))
       emojis.add(Emoji("\ud83d\ude9a", "delivery-truck_1f69a.png"))
       emojis.add(Emoji("\ud83d\ude9b", "articulated-lorry_1f69b.png"))
       emojis.add(Emoji("\ud83d\ude9c", "tractor_1f69c.png"))
       emojis.add(Emoji("\ud83d\ude9d", "monorail_1f69d.png"))
       emojis.add(Emoji("\ud83d\ude9e", "mountain-railway_1f69e.png"))
       emojis.add(Emoji("\ud83d\ude9f", "suspension-railway_1f69f.png"))
       emojis.add(Emoji("\ud83d\udea0", "mountain-cableway_1f6a0.png"))
       emojis.add(Emoji("\ud83d\udea1", "aerial-tramway_1f6a1.png"))
       emojis.add(Emoji("\ud83d\udea2", "ship_1f6a2.png"))
       emojis.add(Emoji("\ud83d\udea3", "rowboat_1f6a3.png"))
       emojis.add(Emoji("\ud83d\udea4", "speedboat_1f6a4.png"))
       emojis.add(Emoji("\ud83d\udea5", "horizontal-traffic-light_1f6a5.png"))
       emojis.add(Emoji("\ud83d\udea6", "vertical-traffic-light_1f6a6.png"))
       emojis.add(Emoji("\ud83d\udea7", "construction-sign_1f6a7.png"))
       emojis.add(Emoji("\ud83d\udea8", "police-cars-revolving-light_1f6a8.png"))
       emojis.add(Emoji("\ud83d\udea9", "triangular-flag-on-post_1f6a9.png"))
       emojis.add(Emoji("\ud83d\udeaa", "door_1f6aa.png"))
       emojis.add(Emoji("\ud83d\udeab", "no-entry-sign_1f6ab.png"))
       emojis.add(Emoji("\ud83d\udeac", "smoking-symbol_1f6ac.png"))
       emojis.add(Emoji("\ud83d\udead", "no-smoking-symbol_1f6ad.png"))
       emojis.add(Emoji("\ud83d\udeae", "put-litter-in-its-place-symbol_1f6ae.png"))
       emojis.add(Emoji("\ud83d\udeaf", "do-not-litter-symbol_1f6af.png"))
       emojis.add(Emoji("\ud83d\udeb0", "potable-water-symbol_1f6b0.png"))
       emojis.add(Emoji("\ud83d\udeb1", "non-potable-water-symbol_1f6b1.png"))
       emojis.add(Emoji("\ud83d\udeb2", "bicycle_1f6b2.png"))
       emojis.add(Emoji("\ud83d\udeb3", "no-bicycles_1f6b3.png"))
       emojis.add(Emoji("\ud83d\udeb4", "bicyclist_1f6b4.png"))
       emojis.add(Emoji("\ud83d\udeb5", "mountain-bicyclist_1f6b5.png"))
       emojis.add(Emoji("\ud83d\udeb6", "pedestrian_1f6b6.png"))
       emojis.add(Emoji("\ud83d\udeb7", "no-pedestrians_1f6b7.png"))
       emojis.add(Emoji("\ud83d\udeb8", "children-crossing_1f6b8.png"))
       emojis.add(Emoji("\ud83d\udeb9", "mens-symbol_1f6b9.png"))
       emojis.add(Emoji("\ud83d\udeba", "womens-symbol_1f6ba.png"))
       emojis.add(Emoji("\ud83d\udebb", "restroom_1f6bb.png"))
       emojis.add(Emoji("\ud83d\udebc", "baby-symbol_1f6bc.png"))
       emojis.add(Emoji("\ud83d\udebd", "toilet_1f6bd.png"))
       emojis.add(Emoji("\ud83d\udebe", "water-closet_1f6be.png"))
       emojis.add(Emoji("\ud83d\udebf", "shower_1f6bf.png"))
       emojis.add(Emoji("\ud83d\udec0", "bath_1f6c0.png"))
       emojis.add(Emoji("\ud83d\udec1", "bathtub_1f6c1.png"))
       emojis.add(Emoji("\ud83d\udec2", "passport-control_1f6c2.png"))
       emojis.add(Emoji("\ud83d\udec3", "customs_1f6c3.png"))
       emojis.add(Emoji("\ud83d\udec4", "baggage-claim_1f6c4.png"))
       emojis.add(Emoji("\ud83d\udec5", "left-luggage_1f6c5.png"))
       emojis.add(Emoji("\ud83d\udecb", "couch-and-lamp_1f6cb.png"))
       emojis.add(Emoji("\ud83d\udecc", "sleeping-accommodation_1f6cc.png"))
       emojis.add(Emoji("\ud83d\udecd", "shopping-bags_1f6cd.png"))
       emojis.add(Emoji("\ud83d\udece", "bellhop-bell_1f6ce.png"))
       emojis.add(Emoji("\ud83d\udecf", "bed_1f6cf.png"))
       emojis.add(Emoji("\ud83d\uded0", "place-of-worship_1f6d0.png"))
       emojis.add(Emoji("\ud83d\uded1", "octagonal-sign_1f6d1.png"))
       emojis.add(Emoji("\ud83d\uded2", "shopping-trolley_1f6d2.png"))
       emojis.add(Emoji("\ud83d\udee0", "hammer-and-wrench_1f6e0.png"))
       emojis.add(Emoji("\ud83d\udee1", "shield_1f6e1.png"))
       emojis.add(Emoji("\ud83d\udee2", "oil-drum_1f6e2.png"))
       emojis.add(Emoji("\ud83d\udee3", "motorway_1f6e3.png"))
       emojis.add(Emoji("\ud83d\udee4", "railway-track_1f6e4.png"))
       emojis.add(Emoji("\ud83d\udee5", "motor-boat_1f6e5.png"))
       emojis.add(Emoji("\ud83d\udee9", "small-airplane_1f6e9.png"))
       emojis.add(Emoji("\ud83d\udeeb", "airplane-departure_1f6eb.png"))
       emojis.add(Emoji("\ud83d\udeec", "airplane-arriving_1f6ec.png"))
       emojis.add(Emoji("\ud83d\udef0", "satellite_1f6f0.png"))
       emojis.add(Emoji("\ud83d\udef3", "passenger-ship_1f6f3.png"))
       emojis.add(Emoji("\ud83d\udef4", "scooter_1f6f4.png"))
       emojis.add(Emoji("\ud83d\udef5", "motor-scooter_1f6f5.png"))
       emojis.add(Emoji("\ud83d\udef6", "canoe_1f6f6.png"))


       emojis.add(Emoji("\ud83e\udd40", "wilted-flower_1f940.png"))
       emojis.add(Emoji("\ud83e\udd41", "drum-with-drumsticks_1f941.png"))

       emojis.add(Emoji("\ud83e\udd44", "spoon_1f944.png"))
       emojis.add(Emoji("\ud83e\udd45", "goal-net_1f945.png"))
       emojis.add(Emoji("\ud83e\udd47", "first-place-medal_1f947.png"))
       emojis.add(Emoji("\ud83e\udd48", "second-place-medal_1f948.png"))
       emojis.add(Emoji("\ud83e\udd49", "third-place-medal_1f949.png"))
       emojis.add(Emoji("\ud83e\udd4a", "boxing-glove_1f94a.png"))
       emojis.add(Emoji("\ud83e\udd4b", "martial-arts-uniform_1f94b.png"))

       emojis.forEach { beginnings.add(it.code[0]) }

   }

}